<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Getting to Know Your Data | AFLEARN Introduction to R using ICAN-ICAR 2025 Survey Data</title>
  <meta name="description" content="<p>AFLEARN
Introduction to R using ICAN-ICAR 2025 Survey Data</p>" />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Getting to Know Your Data | AFLEARN Introduction to R using ICAN-ICAR 2025 Survey Data" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Getting to Know Your Data | AFLEARN Introduction to R using ICAN-ICAR 2025 Survey Data" />
  
  
  

<meta name="author" content="Siphiwe M. Bogatsu" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="part-2-understanding-your-countrys-geographic-structure.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introduction to R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html"><i class="fa fa-check"></i><b>2</b> Getting to Know Your Data</a>
<ul>
<li class="chapter" data-level="2.1" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#learning-objectives"><i class="fa fa-check"></i><b>2.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="2.2" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#setup"><i class="fa fa-check"></i><b>2.2</b> Setup</a></li>
<li class="chapter" data-level="2.3" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#understanding-data-structure-and-dimensions"><i class="fa fa-check"></i><b>2.3</b> Understanding Data Structure and Dimensions</a></li>
<li class="chapter" data-level="2.4" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#quick-data-structure-overview"><i class="fa fa-check"></i><b>2.4</b> Quick Data Structure Overview</a></li>
<li class="chapter" data-level="2.5" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#first-look-at-the-data"><i class="fa fa-check"></i><b>2.5</b> First Look at the Data</a></li>
<li class="chapter" data-level="2.6" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#variable-names-exploration"><i class="fa fa-check"></i><b>2.6</b> Variable Names Exploration</a></li>
<li class="chapter" data-level="2.7" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#checking-variable-types"><i class="fa fa-check"></i><b>2.7</b> Checking Variable Types</a></li>
<li class="chapter" data-level="2.8" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#exercise-1.1-exploring-specific-rows"><i class="fa fa-check"></i><b>2.8</b> Exercise 1.1: Exploring Specific Rows</a></li>
<li class="chapter" data-level="2.9" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#exercise-1.2-exploring-variable-types"><i class="fa fa-check"></i><b>2.9</b> Exercise 1.2: Exploring Variable Types</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="part-2-understanding-your-countrys-geographic-structure.html"><a href="part-2-understanding-your-countrys-geographic-structure.html"><i class="fa fa-check"></i><b>3</b> Part 2: Understanding Your Country’s Geographic Structure</a>
<ul>
<li class="chapter" data-level="3.1" data-path="part-2-understanding-your-countrys-geographic-structure.html"><a href="part-2-understanding-your-countrys-geographic-structure.html#countries-in-the-dataset"><i class="fa fa-check"></i><b>3.1</b> Countries in the Dataset</a></li>
<li class="chapter" data-level="3.2" data-path="part-2-understanding-your-countrys-geographic-structure.html"><a href="part-2-understanding-your-countrys-geographic-structure.html#geographic-structure"><i class="fa fa-check"></i><b>3.2</b> Geographic Structure</a></li>
<li class="chapter" data-level="3.3" data-path="part-2-understanding-your-countrys-geographic-structure.html"><a href="part-2-understanding-your-countrys-geographic-structure.html#your-countrys-geographic-structure"><i class="fa fa-check"></i><b>3.3</b> Your Country’s Geographic Structure</a></li>
<li class="chapter" data-level="3.4" data-path="part-2-understanding-your-countrys-geographic-structure.html"><a href="part-2-understanding-your-countrys-geographic-structure.html#understanding-your-samples-hierarchy"><i class="fa fa-check"></i><b>3.4</b> Understanding Your Sample’s Hierarchy</a></li>
<li class="chapter" data-level="3.5" data-path="part-2-understanding-your-countrys-geographic-structure.html"><a href="part-2-understanding-your-countrys-geographic-structure.html#location-types"><i class="fa fa-check"></i><b>3.5</b> Location Types</a></li>
<li class="chapter" data-level="3.6" data-path="part-2-understanding-your-countrys-geographic-structure.html"><a href="part-2-understanding-your-countrys-geographic-structure.html#exercise-2.1-village-level-exploration"><i class="fa fa-check"></i><b>3.6</b> Exercise 2.1: Village-Level Exploration</a></li>
<li class="chapter" data-level="3.7" data-path="part-2-understanding-your-countrys-geographic-structure.html"><a href="part-2-understanding-your-countrys-geographic-structure.html#exercise-2.2-regional-distribution"><i class="fa fa-check"></i><b>3.7</b> Exercise 2.2: Regional Distribution</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="part-3-basic-data-quality-checks.html"><a href="part-3-basic-data-quality-checks.html"><i class="fa fa-check"></i><b>4</b> Part 3: Basic Data Quality Checks</a>
<ul>
<li class="chapter" data-level="4.1" data-path="part-3-basic-data-quality-checks.html"><a href="part-3-basic-data-quality-checks.html#overall-missing-data-pattern"><i class="fa fa-check"></i><b>4.1</b> Overall Missing Data Pattern</a></li>
<li class="chapter" data-level="4.2" data-path="part-3-basic-data-quality-checks.html"><a href="part-3-basic-data-quality-checks.html#examining-specific-missing-patterns"><i class="fa fa-check"></i><b>4.2</b> Examining Specific Missing Patterns</a></li>
<li class="chapter" data-level="4.3" data-path="part-3-basic-data-quality-checks.html"><a href="part-3-basic-data-quality-checks.html#using-skim-for-quick-overview"><i class="fa fa-check"></i><b>4.3</b> Using <code>skim()</code> for Quick Overview</a></li>
<li class="chapter" data-level="4.4" data-path="part-3-basic-data-quality-checks.html"><a href="part-3-basic-data-quality-checks.html#exploring-specific-variable-types"><i class="fa fa-check"></i><b>4.4</b> Exploring Specific Variable Types</a></li>
<li class="chapter" data-level="4.5" data-path="part-3-basic-data-quality-checks.html"><a href="part-3-basic-data-quality-checks.html#numeric-variable-ranges"><i class="fa fa-check"></i><b>4.5</b> Numeric Variable Ranges</a></li>
<li class="chapter" data-level="4.6" data-path="part-3-basic-data-quality-checks.html"><a href="part-3-basic-data-quality-checks.html#exercise-3.1-missing-data-investigation"><i class="fa fa-check"></i><b>4.6</b> Exercise 3.1: Missing Data Investigation</a></li>
<li class="chapter" data-level="4.7" data-path="part-3-basic-data-quality-checks.html"><a href="part-3-basic-data-quality-checks.html#exercise-3.2-exploring-specific-variable-types"><i class="fa fa-check"></i><b>4.7</b> Exercise 3.2: Exploring Specific Variable Types</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="part-4-creating-basic-summaries.html"><a href="part-4-creating-basic-summaries.html"><i class="fa fa-check"></i><b>5</b> Part 4: Creating Basic Summaries</a>
<ul>
<li class="chapter" data-level="5.1" data-path="part-4-creating-basic-summaries.html"><a href="part-4-creating-basic-summaries.html#summary-table-sample-size-by-country"><i class="fa fa-check"></i><b>5.1</b> Summary Table: Sample Size by Country</a></li>
<li class="chapter" data-level="5.2" data-path="part-4-creating-basic-summaries.html"><a href="part-4-creating-basic-summaries.html#visualizing-geographic-distribution"><i class="fa fa-check"></i><b>5.2</b> Visualizing Geographic Distribution</a></li>
<li class="chapter" data-level="5.3" data-path="part-4-creating-basic-summaries.html"><a href="part-4-creating-basic-summaries.html#creating-a-variable-inventory"><i class="fa fa-check"></i><b>5.3</b> Creating a Variable Inventory</a></li>
<li class="chapter" data-level="5.4" data-path="part-4-creating-basic-summaries.html"><a href="part-4-creating-basic-summaries.html#exercise-4.1-urban-rural-distribution"><i class="fa fa-check"></i><b>5.4</b> Exercise 4.1: Urban-Rural Distribution</a></li>
<li class="chapter" data-level="5.5" data-path="part-4-creating-basic-summaries.html"><a href="part-4-creating-basic-summaries.html#exercise-4.2-create-your-own-visualization"><i class="fa fa-check"></i><b>5.5</b> Exercise 4.2: Create Your Own Visualization</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="summary-and-key-takeaways.html"><a href="summary-and-key-takeaways.html"><i class="fa fa-check"></i><b>6</b> Summary and Key Takeaways</a>
<ul>
<li class="chapter" data-level="6.1" data-path="summary-and-key-takeaways.html"><a href="summary-and-key-takeaways.html#what-we-accomplished-today"><i class="fa fa-check"></i><b>6.1</b> What We Accomplished Today</a></li>
<li class="chapter" data-level="6.2" data-path="summary-and-key-takeaways.html"><a href="summary-and-key-takeaways.html#key-distinctions-we-made-today"><i class="fa fa-check"></i><b>6.2</b> Key Distinctions We Made Today</a></li>
<li class="chapter" data-level="6.3" data-path="summary-and-key-takeaways.html"><a href="summary-and-key-takeaways.html#next-steps"><i class="fa fa-check"></i><b>6.3</b> Next Steps</a></li>
<li class="chapter" data-level="6.4" data-path="summary-and-key-takeaways.html"><a href="summary-and-key-takeaways.html#best-practices-learned"><i class="fa fa-check"></i><b>6.4</b> Best Practices Learned</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="additional-resources.html"><a href="additional-resources.html"><i class="fa fa-check"></i><b>7</b> Additional Resources</a>
<ul>
<li class="chapter" data-level="7.1" data-path="additional-resources.html"><a href="additional-resources.html#useful-functions-reference"><i class="fa fa-check"></i><b>7.1</b> Useful Functions Reference</a></li>
<li class="chapter" data-level="7.2" data-path="additional-resources.html"><a href="additional-resources.html#for-practice"><i class="fa fa-check"></i><b>7.2</b> For Practice</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>8</b> Logistic Regression</a>
<ul>
<li class="chapter" data-level="8.1" data-path="logistic-regression.html"><a href="logistic-regression.html#what-logistic-regression-models"><i class="fa fa-check"></i><b>8.1</b> What logistic regression models</a></li>
<li class="chapter" data-level="8.2" data-path="logistic-regression.html"><a href="logistic-regression.html#simple-versus-multiple-logistic-regression"><i class="fa fa-check"></i><b>8.2</b> Simple versus multiple logistic regression</a></li>
<li class="chapter" data-level="8.3" data-path="logistic-regression.html"><a href="logistic-regression.html#data"><i class="fa fa-check"></i><b>8.3</b> Data</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="logistic-regression.html"><a href="logistic-regression.html#import-subset-and-keep-only-needed-variables"><i class="fa fa-check"></i><b>8.3.1</b> Import, subset, and keep only needed variables</a></li>
<li class="chapter" data-level="8.3.2" data-path="logistic-regression.html"><a href="logistic-regression.html#recode-variables-labels-reference-levels"><i class="fa fa-check"></i><b>8.3.2</b> Recode variables (labels + reference levels)</a></li>
<li class="chapter" data-level="8.3.3" data-path="logistic-regression.html"><a href="logistic-regression.html#why-we-need-survey-design-information"><i class="fa fa-check"></i><b>8.3.3</b> Why we need survey design information</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="logistic-regression.html"><a href="logistic-regression.html#simple-logistic-regression"><i class="fa fa-check"></i><b>8.4</b> Simple Logistic Regression</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="logistic-regression.html"><a href="logistic-regression.html#continuous-predictor-childs-age"><i class="fa fa-check"></i><b>8.4.1</b> Continuous predictor: child’s age</a></li>
<li class="chapter" data-level="8.4.2" data-path="logistic-regression.html"><a href="logistic-regression.html#categorical-predictor-example-books"><i class="fa fa-check"></i><b>8.4.2</b> Categorical predictor example: Books</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="logistic-regression.html"><a href="logistic-regression.html#multiple-binary-logistic-regression"><i class="fa fa-check"></i><b>8.5</b> Multiple binary logistic regression</a></li>
<li class="chapter" data-level="8.6" data-path="logistic-regression.html"><a href="logistic-regression.html#interaction"><i class="fa fa-check"></i><b>8.6</b> Interaction</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="logistic-regression.html"><a href="logistic-regression.html#interpretation-of-age-sex-and-the-agesex-interaction"><i class="fa fa-check"></i><b>8.6.1</b> Interpretation of age, sex, and the age*sex interaction</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="logistic-regression.html"><a href="logistic-regression.html#reporting-results"><i class="fa fa-check"></i><b>8.7</b> Reporting Results</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="a-caucus-race-and-a-long-tale.html"><a href="a-caucus-race-and-a-long-tale.html"><i class="fa fa-check"></i><b>9</b> A caucus-race and a long tale</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"><p>AFLEARN
Introduction to R using ICAN-ICAR 2025 Survey Data</p></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="getting-to-know-your-data" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Chapter 2</span> Getting to Know Your Data<a href="getting-to-know-your-data.html#getting-to-know-your-data" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="learning-objectives" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Learning Objectives<a href="getting-to-know-your-data.html#learning-objectives" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>By the end of this session, you will be able to:</p>
<ol style="list-style-type: decimal">
<li>Load and inspect the structure of the PAL ICAN/ICAR dataset</li>
<li>Understand the dimensions and organization of the data</li>
<li>Explore variable names, types, and their correspondence to the codebook</li>
<li>Conduct basic data quality checks</li>
<li>Create simple data summaries for different variable types</li>
</ol>
<p>In the previous session, we learned how the ICAN–ICAR survey data was sampled and created a survey design object that allows us to make population-level estimates.</p>
<p>Before we analyse any outcomes, we must first understand what the data actually contains, how it is structured, and whether it is ready for analysis. We assume that a valid survey design object has already been created. This session focuses on understanding the underlying data that feed into that design.} This session focuses on — not inference.</p>
<p>The ICAN-ICAR 2025 survey is a foundational learning assessment focused on children aged 5-16 years. The survey collects data on: child demographics and enrollment status, household characteristics and assets, literacy and numeracy assessment results, and parental information</p>
</div>
<div id="setup" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Setup<a href="getting-to-know-your-data.html#setup" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="getting-to-know-your-data.html#cb1-1" tabindex="-1"></a><span class="co"># Load required packages</span></span>
<span id="cb1-2"><a href="getting-to-know-your-data.html#cb1-2" tabindex="-1"></a><span class="fu">library</span>(tidyverse)   <span class="co"># Data manipulation and visualization</span></span></code></pre></div>
<pre><code>## Warning: package &#39;tidyverse&#39; was built under R version 4.5.2</code></pre>
<pre><code>## Warning: package &#39;ggplot2&#39; was built under R version 4.5.1</code></pre>
<pre><code>## Warning: package &#39;tibble&#39; was built under R version 4.5.2</code></pre>
<pre><code>## Warning: package &#39;tidyr&#39; was built under R version 4.5.1</code></pre>
<pre><code>## Warning: package &#39;purrr&#39; was built under R version 4.5.2</code></pre>
<pre><code>## Warning: package &#39;dplyr&#39; was built under R version 4.5.1</code></pre>
<pre><code>## Warning: package &#39;stringr&#39; was built under R version 4.5.1</code></pre>
<pre><code>## Warning: package &#39;lubridate&#39; was built under R version 4.5.1</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="getting-to-know-your-data.html#cb10-1" tabindex="-1"></a><span class="fu">library</span>(readr)       <span class="co"># Reading CSV files</span></span>
<span id="cb10-2"><a href="getting-to-know-your-data.html#cb10-2" tabindex="-1"></a><span class="fu">library</span>(skimr)       <span class="co"># Quick data summaries</span></span></code></pre></div>
<pre><code>## Warning: package &#39;skimr&#39; was built under R version 4.5.1</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="getting-to-know-your-data.html#cb12-1" tabindex="-1"></a><span class="fu">library</span>(janitor)     <span class="co"># Data cleaning helpers</span></span></code></pre></div>
<pre><code>## Warning: package &#39;janitor&#39; was built under R version 4.5.1</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="getting-to-know-your-data.html#cb14-1" tabindex="-1"></a><span class="fu">library</span>(survey)      <span class="co"># Survey analysis</span></span></code></pre></div>
<pre><code>## Warning: package &#39;survey&#39; was built under R version 4.5.1</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="getting-to-know-your-data.html#cb16-1" tabindex="-1"></a><span class="co"># Load the PAL ICAN/ICAR dataset</span></span>
<span id="cb16-2"><a href="getting-to-know-your-data.html#cb16-2" tabindex="-1"></a></span>
<span id="cb16-3"><a href="getting-to-know-your-data.html#cb16-3" tabindex="-1"></a>data_weighted <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/2025_PAL_ICAN-ICAR_data.csv&quot;</span>)</span></code></pre></div>
</div>
<div id="understanding-data-structure-and-dimensions" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Understanding Data Structure and Dimensions<a href="getting-to-know-your-data.html#understanding-data-structure-and-dimensions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>Core Question:</strong> <em>What is the shape of this data?</em></p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="getting-to-know-your-data.html#cb17-1" tabindex="-1"></a><span class="co"># How many rows (observations) and columns (variables)?</span></span>
<span id="cb17-2"><a href="getting-to-know-your-data.html#cb17-2" tabindex="-1"></a><span class="fu">nrow</span>(data_weighted)</span></code></pre></div>
<pre><code>## [1] 89141</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="getting-to-know-your-data.html#cb19-1" tabindex="-1"></a><span class="fu">ncol</span>(data_weighted)</span></code></pre></div>
<pre><code>## [1] 142</code></pre>
<p>We have 89141 observations spread across 142 variables. Each row represents a <strong>child</strong> (aged 5-16 years) nested within a household, village, and country. Each column represents a survey variable. Note that the sampling was done at the household level, but learning assessments were conducted for all eligible children within selected households. This means multiple children can come from the same household.</p>
</div>
<div id="quick-data-structure-overview" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> Quick Data Structure Overview<a href="getting-to-know-your-data.html#quick-data-structure-overview" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="getting-to-know-your-data.html#cb21-1" tabindex="-1"></a><span class="co"># Get a glimpse of the data structure</span></span>
<span id="cb21-2"><a href="getting-to-know-your-data.html#cb21-2" tabindex="-1"></a><span class="fu">glimpse</span>(data_weighted)</span></code></pre></div>
<pre><code>## Rows: 89,141
## Columns: 142
## $ CountryName          &lt;chr&gt; &quot;Mozambique&quot;, &quot;Mozambique&quot;, &quot;Mozambique&quot;, &quot;Mozamb…
## $ Tier_One_Unit        &lt;chr&gt; &quot;Niassa&quot;, &quot;Niassa&quot;, &quot;Niassa&quot;, &quot;Niassa&quot;, &quot;Niassa&quot;,…
## $ VillageID            &lt;chr&gt; &quot;c101&quot;, &quot;c101&quot;, &quot;c101&quot;, &quot;c101&quot;, &quot;c101&quot;, &quot;c101&quot;, &quot;…
## $ Location             &lt;chr&gt; &quot;Urban&quot;, &quot;Urban&quot;, &quot;Urban&quot;, &quot;Urban&quot;, &quot;Urban&quot;, &quot;Urb…
## $ HHID                 &lt;chr&gt; &quot;uuid:f5808f62-6a22-4247-ae68-9eb891657449&quot;, &quot;uui…
## $ SubmissionDate       &lt;chr&gt; &quot;9/23/2025, 5:02:46 PM&quot;, &quot;9/23/2025, 5:02:47 PM&quot;,…
## $ duration             &lt;dbl&gt; 979, 986, 2167, 2078, 1251, 2199, 2889, 1588, 220…
## $ hh06a                &lt;dbl&gt; 4, 7, 6, 6, 5, 5, 5, 4, 4, 5, 7, 9, 5, 13, 5, 6, …
## $ hh06b                &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
## $ hh06c                &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1…
## $ hh06d                &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1…
## $ hh07a                &lt;dbl&gt; 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2…
## $ hh07b                &lt;dbl&gt; 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2…
## $ hh07c                &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
## $ hh07d                &lt;dbl&gt; 1, 1, 1, 4, 4, 4, 1, 1, 4, 4, 3, 4, 7, 3, 1, 4, 1…
## $ hh07e                &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
## $ hh07f                &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
## $ hh07g                &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1…
## $ hh07h                &lt;dbl&gt; 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1…
## $ hh07i                &lt;dbl&gt; 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1…
## $ hh07j                &lt;dbl&gt; 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1…
## $ hh07k                &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1…
## $ hh07l                &lt;dbl&gt; 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0…
## $ hh07m                &lt;dbl&gt; 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
## $ hh07n                &lt;dbl&gt; 0, 0, 1, 0, NA, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, …
## $ hh07o                &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ hh07p                &lt;dbl&gt; 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0…
## $ hh07p_3              &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ hh07q                &lt;dbl&gt; 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ ChildID              &lt;chr&gt; &quot;uuid:f5808f62-6a22-4247-ae68-9eb891657449_child1…
## $ ch02                 &lt;dbl&gt; 8, 12, 8, 9, 10, 13, 8, 8, 16, 8, 7, 9, 10, 7, 11…
## $ ch03                 &lt;dbl&gt; 2, 2, 1, 1, 2, 1, 1, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2…
## $ ch04a                &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
## $ ch04b                &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2…
## $ ch04c                &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
## $ ch04d                &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
## $ ch04e                &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
## $ ch04f                &lt;dbl&gt; 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1…
## $ ch05                 &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1…
## $ ch06a                &lt;dbl&gt; 4, 6, 3, 5, 2, 7, 3, 3, 10, 1, 2, 2, 4, 2, NA, 8,…
## $ ch06b                &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, NA, 1, …
## $ ch06c                &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, NA, 1, …
## $ ch06d                &lt;dbl&gt; 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, NA, 1, …
## $ ch06e                &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NA, 0, …
## $ ch07a                &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ ch07b                &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ ch07c                &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ ch07d                &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ ch08                 &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1…
## $ ch09                 &lt;dbl&gt; 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1…
## $ ch10a                &lt;dbl&gt; 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, NA, 1, …
## $ ch10b                &lt;dbl&gt; 2, 3, 4, NA, NA, NA, NA, 1, 1, 1, 7, NA, 7, 7, NA…
## $ ch10c                &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 2, 2, 0…
## $ pt00                 &lt;dbl&gt; 1, 1, 3, 3, 3, 0, 3, 3, 3, 2, 0, 0, 1, 0, 3, 1, 0…
## $ pt01b                &lt;dbl&gt; 28, 40, 47, 26, 36, NA, 52, 26, 36, NA, NA, NA, 2…
## $ pt01c                &lt;dbl&gt; 1, 1, 1, 0, 0, NA, 1, 1, 0, NA, NA, NA, 1, NA, 0,…
## $ pt01d                &lt;dbl&gt; 1, 1, 1, NA, NA, NA, 1, 1, NA, NA, NA, NA, 1, NA,…
## $ pt01e                &lt;dbl&gt; 0, 0, 0, 0, 0, NA, 0, 1, 0, NA, NA, NA, 1, NA, 0,…
## $ pt01f                &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, 4, NA, NA, NA, NA, 3,…
## $ pt02b                &lt;dbl&gt; NA, NA, 63, 30, 50, NA, 59, 31, 43, 40, NA, NA, N…
## $ pt02c                &lt;dbl&gt; NA, NA, 1, 1, 1, NA, 1, 1, 1, 1, NA, NA, NA, NA, …
## $ pt02d                &lt;dbl&gt; NA, NA, 2, 2, 1, NA, 2, 2, 2, 2, NA, NA, NA, NA, …
## $ pt02e                &lt;dbl&gt; NA, NA, 1, 1, 1, NA, 1, 1, 1, 1, NA, NA, NA, NA, …
## $ pt02f                &lt;dbl&gt; NA, NA, 4, 4, 3, NA, 4, 4, 4, 1, NA, NA, NA, NA, …
## $ assessment           &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
## $ sample               &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1…
## $ l1.1                 &lt;dbl&gt; 1, 2, 0, 2, 1, 1, 1, 2, 2, 2, 2, 1, 0, 0, 2, 1, 2…
## $ l1.2                 &lt;dbl&gt; 1, 2, 0, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 0, 2, 1, 1…
## $ l1.3                 &lt;dbl&gt; 1, 1, 0, 2, 1, 1, 2, 2, 2, 0, 2, 2, 1, 0, 2, 1, 1…
## $ l1.4                 &lt;dbl&gt; 1, 2, 0, 2, 1, 1, 2, 2, 1, 1, 2, 1, 0, 0, 2, 1, 1…
## $ l2.1                 &lt;dbl&gt; 0, 2, 0, 2, 1, 2, 0, 2, 2, 1, 1, 0, 2, 0, 2, 2, 2…
## $ l2.2                 &lt;dbl&gt; 0, 1, 0, 2, 1, 2, 2, 2, 2, 1, 1, 0, 1, 0, 2, 1, 1…
## $ l2.3                 &lt;dbl&gt; 0, 2, 0, 2, 1, 2, 2, 2, 2, 1, 1, 1, 1, 0, 2, 1, 1…
## $ l2.4                 &lt;dbl&gt; 0, 2, 0, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 0, 2, 1, 1…
## $ l2.5                 &lt;dbl&gt; 0, 2, 0, 2, 1, 1, 1, 2, 2, 0, 1, 1, 1, 0, 2, 1, 1…
## $ l3.1                 &lt;dbl&gt; NA, 2, NA, 2, NA, 0, NA, 2, 1, NA, NA, NA, NA, NA…
## $ l3.2                 &lt;dbl&gt; NA, 2, NA, 2, NA, 0, NA, 2, 1, NA, NA, NA, NA, NA…
## $ l3.3                 &lt;dbl&gt; NA, 2, NA, 2, NA, 0, NA, 2, 2, NA, NA, NA, NA, NA…
## $ l3.4                 &lt;dbl&gt; NA, 2, NA, 2, NA, 0, NA, 2, 2, NA, NA, NA, NA, NA…
## $ l3.5                 &lt;dbl&gt; NA, 2, NA, 2, NA, 0, NA, 2, 1, NA, NA, NA, NA, NA…
## $ l4.1                 &lt;dbl&gt; NA, 2, NA, 2, NA, 2, NA, 2, 2, NA, NA, NA, NA, NA…
## $ l4.2                 &lt;dbl&gt; NA, 2, NA, 2, NA, 1, NA, 2, 2, NA, NA, NA, NA, NA…
## $ l4.3                 &lt;dbl&gt; NA, 2, NA, 2, NA, 2, NA, 2, 2, NA, NA, NA, NA, NA…
## $ l4.4                 &lt;dbl&gt; NA, 2, NA, 2, NA, 2, NA, 2, 2, NA, NA, NA, NA, NA…
## $ l4.5                 &lt;dbl&gt; NA, 2, NA, 2, NA, 1, NA, 2, 2, NA, NA, NA, NA, NA…
## $ l4.6                 &lt;dbl&gt; NA, 2, NA, 2, NA, 2, NA, 2, 1, NA, NA, NA, NA, NA…
## $ l5.1                 &lt;dbl&gt; NA, 2, NA, 2, NA, NA, NA, 2, NA, NA, NA, NA, NA, …
## $ l5.2                 &lt;dbl&gt; NA, 2, NA, 2, NA, NA, NA, 2, NA, NA, NA, NA, NA, …
## $ l5.3                 &lt;dbl&gt; NA, 2, NA, 2, NA, NA, NA, 2, NA, NA, NA, NA, NA, …
## $ l5.4                 &lt;dbl&gt; NA, 2, NA, 2, NA, NA, NA, 2, NA, NA, NA, NA, NA, …
## $ l5.5                 &lt;dbl&gt; NA, 2, NA, 2, NA, NA, NA, 2, NA, NA, NA, NA, NA, …
## $ l6.1                 &lt;dbl&gt; NA, 2, NA, 2, NA, NA, NA, 2, NA, NA, NA, NA, NA, …
## $ l6.2                 &lt;dbl&gt; NA, 2, NA, 1, NA, NA, NA, 2, NA, NA, NA, NA, NA, …
## $ l6.3                 &lt;dbl&gt; NA, 2, NA, 1, NA, NA, NA, 1, NA, NA, NA, NA, NA, …
## $ l6.4                 &lt;dbl&gt; NA, 2, NA, 2, NA, NA, NA, 2, NA, NA, NA, NA, NA, …
## $ l6.5                 &lt;dbl&gt; NA, 2, NA, 2, NA, NA, NA, 2, NA, NA, NA, NA, NA, …
## $ n1                   &lt;dbl&gt; 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2…
## $ n2                   &lt;dbl&gt; 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2…
## $ n3                   &lt;dbl&gt; 1, 2, 2, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1…
## $ n4                   &lt;dbl&gt; 2, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 1…
## $ n5                   &lt;dbl&gt; 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 0, 1, 2, 2, 1…
## $ n6                   &lt;dbl&gt; 2, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 0, 1, 2, 2, 1…
## $ n7                   &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 0, 2, 2, 1…
## $ n8                   &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1…
## $ n9                   &lt;dbl&gt; 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1…
## $ n10                  &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 2, 2, 1…
## $ n11                  &lt;dbl&gt; 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2…
## $ n12                  &lt;dbl&gt; 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2…
## $ n13                  &lt;dbl&gt; 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2…
## $ n14                  &lt;dbl&gt; 2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2…
## $ n15                  &lt;dbl&gt; 2, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 2, 1, 2…
## $ n16                  &lt;dbl&gt; 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2…
## $ n17                  &lt;dbl&gt; 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2…
## $ n18                  &lt;dbl&gt; 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2…
## $ n19                  &lt;dbl&gt; 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2…
## $ n20                  &lt;dbl&gt; 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2…
## $ n21                  &lt;dbl&gt; 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2…
## $ n22                  &lt;dbl&gt; 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2…
## $ n23                  &lt;dbl&gt; 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 1, 2, 2, 1, 2, 1, 2…
## $ n24                  &lt;dbl&gt; 2, 2, 2, 2, 0, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 1, 2…
## $ n25                  &lt;dbl&gt; 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2…
## $ n26                  &lt;dbl&gt; 1, 2, 1, 2, 0, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2…
## $ n27                  &lt;dbl&gt; 1, 1, 1, 2, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 2, 2, 1…
## $ n28                  &lt;dbl&gt; 1, 1, 1, 1, 0, 1, 2, 2, 2, 2, 1, 1, 0, 1, 2, 2, 1…
## $ n29                  &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 2, 1, 2, 2, 1…
## $ n30                  &lt;dbl&gt; 1, 1, 1, 1, 0, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1…
## $ n31                  &lt;dbl&gt; NA, NA, NA, 1, NA, NA, 1, 1, 2, NA, NA, NA, NA, N…
## $ n32                  &lt;dbl&gt; NA, NA, NA, NA, NA, NA, 1, 1, 1, 0, NA, NA, NA, N…
## $ n33                  &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, 2, NA, 0, 1, NA, 1, N…
## $ n34                  &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, 2, NA, 1, NA, NA, NA,…
## $ n35                  &lt;dbl&gt; NA, NA, NA, NA, NA, NA, 1, 2, 2, 1, NA, NA, NA, N…
## $ n36                  &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, 2, NA, 1, NA, NA, NA,…
## $ icar_assess_time     &lt;dbl&gt; 0.7833333, 5.5166667, 1.7333333, 4.2166667, 0.616…
## $ ican_assess_time     &lt;dbl&gt; 4.866667, 3.333333, 4.333333, 4.116667, 7.383333,…
## $ SubmissionDate_clean &lt;date&gt; 2025-09-23, 2025-09-23, 2025-09-23, 2025-09-23, …
## $ ass_lang_str         &lt;chr&gt; &quot;Portuguese&quot;, &quot;Portuguese&quot;, &quot;Portuguese&quot;, &quot;Portug…
## $ ass_home_lang        &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
## $ enr_status           &lt;chr&gt; &quot;Currently Enrolled&quot;, &quot;Currently Enrolled&quot;, &quot;Curr…
## $ HH_Weight_Provided   &lt;dbl&gt; 874.2795, 874.2795, 874.2795, 874.2795, 874.2795,…
## $ MPL_math             &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0…
## $ MPL_lang             &lt;dbl&gt; 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ MPL_both             &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0…</code></pre>
<p><strong>What does this tell us?</strong></p>
<ul>
<li>Variable names (on the left)</li>
<li>Variable types (<code>&lt;chr&gt;</code> for character/text, <code>&lt;dbl&gt;</code> for numeric)</li>
<li>First few values for each variable</li>
</ul>
</div>
<div id="first-look-at-the-data" class="section level2 hasAnchor" number="2.5">
<h2><span class="header-section-number">2.5</span> First Look at the Data<a href="getting-to-know-your-data.html#first-look-at-the-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="getting-to-know-your-data.html#cb23-1" tabindex="-1"></a><span class="co"># View first 5 rows</span></span>
<span id="cb23-2"><a href="getting-to-know-your-data.html#cb23-2" tabindex="-1"></a><span class="fu">head</span>(data_weighted)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 142
##   CountryName Tier_One_Unit VillageID Location HHID      SubmissionDate duration
##   &lt;chr&gt;       &lt;chr&gt;         &lt;chr&gt;     &lt;chr&gt;    &lt;chr&gt;     &lt;chr&gt;             &lt;dbl&gt;
## 1 Mozambique  Niassa        c101      Urban    uuid:f58… 9/23/2025, 5:…      979
## 2 Mozambique  Niassa        c101      Urban    uuid:b98… 9/23/2025, 5:…      986
## 3 Mozambique  Niassa        c101      Urban    uuid:261… 9/23/2025, 5:…     2167
## 4 Mozambique  Niassa        c101      Urban    uuid:d46… 9/23/2025, 5:…     2078
## 5 Mozambique  Niassa        c101      Urban    uuid:df9… 9/23/2025, 5:…     1251
## 6 Mozambique  Niassa        c101      Urban    uuid:ade… 9/23/2025, 5:…     2199
## # ℹ 135 more variables: hh06a &lt;dbl&gt;, hh06b &lt;dbl&gt;, hh06c &lt;dbl&gt;, hh06d &lt;dbl&gt;,
## #   hh07a &lt;dbl&gt;, hh07b &lt;dbl&gt;, hh07c &lt;dbl&gt;, hh07d &lt;dbl&gt;, hh07e &lt;dbl&gt;,
## #   hh07f &lt;dbl&gt;, hh07g &lt;dbl&gt;, hh07h &lt;dbl&gt;, hh07i &lt;dbl&gt;, hh07j &lt;dbl&gt;,
## #   hh07k &lt;dbl&gt;, hh07l &lt;dbl&gt;, hh07m &lt;dbl&gt;, hh07n &lt;dbl&gt;, hh07o &lt;dbl&gt;,
## #   hh07p &lt;dbl&gt;, hh07p_3 &lt;dbl&gt;, hh07q &lt;dbl&gt;, ChildID &lt;chr&gt;, ch02 &lt;dbl&gt;,
## #   ch03 &lt;dbl&gt;, ch04a &lt;dbl&gt;, ch04b &lt;dbl&gt;, ch04c &lt;dbl&gt;, ch04d &lt;dbl&gt;,
## #   ch04e &lt;dbl&gt;, ch04f &lt;dbl&gt;, ch05 &lt;dbl&gt;, ch06a &lt;dbl&gt;, ch06b &lt;dbl&gt;, …</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="getting-to-know-your-data.html#cb25-1" tabindex="-1"></a><span class="co"># View last 5 rows </span></span>
<span id="cb25-2"><a href="getting-to-know-your-data.html#cb25-2" tabindex="-1"></a><span class="fu">tail</span>(data_weighted)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 142
##   CountryName Tier_One_Unit VillageID Location HHID      SubmissionDate duration
##   &lt;chr&gt;       &lt;chr&gt;         &lt;chr&gt;     &lt;chr&gt;    &lt;chr&gt;     &lt;chr&gt;             &lt;dbl&gt;
## 1 Tanzania    Tanga         v472      Rural    uuid:b07… 9/27/2025, 6:…     2470
## 2 Tanzania    Tanga         v472      Rural    uuid:fa7… 9/27/2025, 6:…     3105
## 3 Tanzania    Tanga         v472      Rural    uuid:fa7… 9/27/2025, 6:…     3105
## 4 Tanzania    Tanga         v472      Rural    uuid:fe8… 9/27/2025, 6:…     1896
## 5 Tanzania    Tanga         v472      Rural    uuid:ae8… 9/29/2025, 2:…     4161
## 6 Tanzania    Tanga         v472      Rural    uuid:ae8… 9/29/2025, 2:…     4161
## # ℹ 135 more variables: hh06a &lt;dbl&gt;, hh06b &lt;dbl&gt;, hh06c &lt;dbl&gt;, hh06d &lt;dbl&gt;,
## #   hh07a &lt;dbl&gt;, hh07b &lt;dbl&gt;, hh07c &lt;dbl&gt;, hh07d &lt;dbl&gt;, hh07e &lt;dbl&gt;,
## #   hh07f &lt;dbl&gt;, hh07g &lt;dbl&gt;, hh07h &lt;dbl&gt;, hh07i &lt;dbl&gt;, hh07j &lt;dbl&gt;,
## #   hh07k &lt;dbl&gt;, hh07l &lt;dbl&gt;, hh07m &lt;dbl&gt;, hh07n &lt;dbl&gt;, hh07o &lt;dbl&gt;,
## #   hh07p &lt;dbl&gt;, hh07p_3 &lt;dbl&gt;, hh07q &lt;dbl&gt;, ChildID &lt;chr&gt;, ch02 &lt;dbl&gt;,
## #   ch03 &lt;dbl&gt;, ch04a &lt;dbl&gt;, ch04b &lt;dbl&gt;, ch04c &lt;dbl&gt;, ch04d &lt;dbl&gt;,
## #   ch04e &lt;dbl&gt;, ch04f &lt;dbl&gt;, ch05 &lt;dbl&gt;, ch06a &lt;dbl&gt;, ch06b &lt;dbl&gt;, …</code></pre>
</div>
<div id="variable-names-exploration" class="section level2 hasAnchor" number="2.6">
<h2><span class="header-section-number">2.6</span> Variable Names Exploration<a href="getting-to-know-your-data.html#variable-names-exploration" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s look at all variable names systematically:</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="getting-to-know-your-data.html#cb27-1" tabindex="-1"></a><span class="co"># List all variable names</span></span>
<span id="cb27-2"><a href="getting-to-know-your-data.html#cb27-2" tabindex="-1"></a><span class="fu">names</span>(data_weighted)</span></code></pre></div>
<p><strong>Together, let’s answer:</strong></p>
<ol style="list-style-type: decimal">
<li>Can you identify the <strong>design variables</strong>? (e.g., CountryName, VillageID, HHID, ChildID)</li>
<li>Which variables are <strong>household-level</strong>? (Look for <code>hh</code> prefix - household characteristics)</li>
<li>Which variables are <strong>child-level</strong>? (Look for <code>ch</code> prefix - child demographics, enrollment)</li>
<li>Which variables are <strong>assessment outcomes</strong>? (Look for <code>l</code> for literacy, <code>n</code> for numeracy, <code>MPL</code>)</li>
<li>Which are <strong>administrative/metadata</strong>? (e.g., SubmissionDate, duration)</li>
</ol>
</div>
<div id="checking-variable-types" class="section level2 hasAnchor" number="2.7">
<h2><span class="header-section-number">2.7</span> Checking Variable Types<a href="getting-to-know-your-data.html#checking-variable-types" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="getting-to-know-your-data.html#cb28-1" tabindex="-1"></a><span class="co"># Look at variable types using glimpse (we used this earlier!)</span></span>
<span id="cb28-2"><a href="getting-to-know-your-data.html#cb28-2" tabindex="-1"></a><span class="fu">glimpse</span>(data_weighted)</span>
<span id="cb28-3"><a href="getting-to-know-your-data.html#cb28-3" tabindex="-1"></a></span>
<span id="cb28-4"><a href="getting-to-know-your-data.html#cb28-4" tabindex="-1"></a><span class="co"># We can also look at specific variables more closely</span></span>
<span id="cb28-5"><a href="getting-to-know-your-data.html#cb28-5" tabindex="-1"></a><span class="fu">str</span>(data_weighted<span class="sc">$</span>CountryName)    <span class="co"># Character variable</span></span>
<span id="cb28-6"><a href="getting-to-know-your-data.html#cb28-6" tabindex="-1"></a><span class="fu">str</span>(data_weighted<span class="sc">$</span>ch02)           <span class="co"># Numeric variable (age)</span></span>
<span id="cb28-7"><a href="getting-to-know-your-data.html#cb28-7" tabindex="-1"></a><span class="fu">str</span>(data_weighted<span class="sc">$</span>enr_status)     <span class="co"># Character variable</span></span></code></pre></div>
<p><strong>Let’s discuss together:</strong></p>
<ul>
<li>Look at the output - what does <code>&lt;chr&gt;</code> mean? What about <code>&lt;dbl&gt;</code>?</li>
<li>Can you spot which variables are character (text) vs numeric?</li>
<li>Do the types make sense for what each variable represents?</li>
</ul>
</div>
<div id="exercise-1.1-exploring-specific-rows" class="section level2 hasAnchor" number="2.8">
<h2><span class="header-section-number">2.8</span> Exercise 1.1: Exploring Specific Rows<a href="getting-to-know-your-data.html#exercise-1.1-exploring-specific-rows" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="getting-to-know-your-data.html#cb29-1" tabindex="-1"></a><span class="co"># YOUR TURN: View rows 10 to 20 of the dataset</span></span>
<span id="cb29-2"><a href="getting-to-know-your-data.html#cb29-2" tabindex="-1"></a><span class="co"># Hint: Use slice() or bracket notation</span></span>
<span id="cb29-3"><a href="getting-to-know-your-data.html#cb29-3" tabindex="-1"></a>data_weighted[<span class="dv">10</span><span class="sc">:</span><span class="dv">20</span>, ]</span></code></pre></div>
</div>
<div id="exercise-1.2-exploring-variable-types" class="section level2 hasAnchor" number="2.9">
<h2><span class="header-section-number">2.9</span> Exercise 1.2: Exploring Variable Types<a href="getting-to-know-your-data.html#exercise-1.2-exploring-variable-types" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="getting-to-know-your-data.html#cb30-1" tabindex="-1"></a><span class="co"># YOUR TURN: Look at the structure of these three variables:</span></span>
<span id="cb30-2"><a href="getting-to-know-your-data.html#cb30-2" tabindex="-1"></a><span class="co"># - hh07a (household roofing material)</span></span>
<span id="cb30-3"><a href="getting-to-know-your-data.html#cb30-3" tabindex="-1"></a><span class="co"># - ch03 (child&#39;s sex)</span></span>
<span id="cb30-4"><a href="getting-to-know-your-data.html#cb30-4" tabindex="-1"></a><span class="co"># - MPL_math (math proficiency level)</span></span>
<span id="cb30-5"><a href="getting-to-know-your-data.html#cb30-5" tabindex="-1"></a><span class="co"># Use str() to examine each one</span></span>
<span id="cb30-6"><a href="getting-to-know-your-data.html#cb30-6" tabindex="-1"></a><span class="co"># What type is each variable? Does it make sense?</span></span>
<span id="cb30-7"><a href="getting-to-know-your-data.html#cb30-7" tabindex="-1"></a></span>
<span id="cb30-8"><a href="getting-to-know-your-data.html#cb30-8" tabindex="-1"></a><span class="fu">str</span>(data_weighted<span class="sc">$</span>hh07a)</span>
<span id="cb30-9"><a href="getting-to-know-your-data.html#cb30-9" tabindex="-1"></a><span class="fu">str</span>(data_weighted<span class="sc">$</span>ch03)</span>
<span id="cb30-10"><a href="getting-to-know-your-data.html#cb30-10" tabindex="-1"></a><span class="fu">str</span>(data_weighted<span class="sc">$</span>MPL_math)</span></code></pre></div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="part-2-understanding-your-countrys-geographic-structure.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/siphiwebogatsu/DF-draft/edit/main/01-get-to-know-your-data.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": "https://github.comsiphiwebogatsu/DF-draft/blob/main/01-get-to-know-your-data.Rmd",
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
