<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Understanding distributions | AFLEARN Introduction to R using ICAN-ICAR 2025 Survey Data</title>
  <meta name="description" content="<p>AFLEARN
Introduction to R using ICAN-ICAR 2025 Survey Data</p>" />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Understanding distributions | AFLEARN Introduction to R using ICAN-ICAR 2025 Survey Data" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Understanding distributions | AFLEARN Introduction to R using ICAN-ICAR 2025 Survey Data" />
  
  
  

<meta name="author" content="Siphiwe M. Bogatsu" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="survey-design-sampling-and-weighting.html"/>
<link rel="next" href="central-tendency-and-dispersion.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introduction to R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="survey-design-sampling-and-weighting.html"><a href="survey-design-sampling-and-weighting.html"><i class="fa fa-check"></i><b>2</b> Survey Design, Sampling, and Weighting</a>
<ul>
<li class="chapter" data-level="2.1" data-path="survey-design-sampling-and-weighting.html"><a href="survey-design-sampling-and-weighting.html#survey-sampling-and-design"><i class="fa fa-check"></i><b>2.1</b> Survey sampling and design</a></li>
<li class="chapter" data-level="2.2" data-path="survey-design-sampling-and-weighting.html"><a href="survey-design-sampling-and-weighting.html#survey-weights-and-design-based-inference"><i class="fa fa-check"></i><b>2.2</b> Survey weights and design-based inference</a></li>
<li class="chapter" data-level="2.3" data-path="survey-design-sampling-and-weighting.html"><a href="survey-design-sampling-and-weighting.html#practice-exercises"><i class="fa fa-check"></i><b>2.3</b> Practice exercises</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="understanding-distributions.html"><a href="understanding-distributions.html"><i class="fa fa-check"></i><b>3</b> Understanding distributions</a>
<ul>
<li class="chapter" data-level="3.1" data-path="understanding-distributions.html"><a href="understanding-distributions.html#getting-oriented-to-the-data"><i class="fa fa-check"></i><b>3.1</b> Getting oriented to the data</a></li>
<li class="chapter" data-level="3.2" data-path="understanding-distributions.html"><a href="understanding-distributions.html#levels-of-measurement"><i class="fa fa-check"></i><b>3.2</b> Levels of measurement</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="understanding-distributions.html"><a href="understanding-distributions.html#continuous-level"><i class="fa fa-check"></i><b>3.2.1</b> Continuous level</a></li>
<li class="chapter" data-level="3.2.2" data-path="understanding-distributions.html"><a href="understanding-distributions.html#ordinal-level"><i class="fa fa-check"></i><b>3.2.2</b> Ordinal level</a></li>
<li class="chapter" data-level="3.2.3" data-path="understanding-distributions.html"><a href="understanding-distributions.html#categorical-level"><i class="fa fa-check"></i><b>3.2.3</b> Categorical level</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="understanding-distributions.html"><a href="understanding-distributions.html#weighted-summaries-using-the-survey-design"><i class="fa fa-check"></i><b>3.3</b> Weighted summaries using the survey design</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="understanding-distributions.html"><a href="understanding-distributions.html#weighted-proportions-and-means"><i class="fa fa-check"></i><b>3.3.1</b> Weighted proportions and means</a></li>
<li class="chapter" data-level="3.3.2" data-path="understanding-distributions.html"><a href="understanding-distributions.html#weighted-frequency-tables"><i class="fa fa-check"></i><b>3.3.2</b> Weighted frequency tables</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="understanding-distributions.html"><a href="understanding-distributions.html#household-level-variables-in-a-child-level-file"><i class="fa fa-check"></i><b>3.4</b> Household-level variables in a child-level file</a></li>
<li class="chapter" data-level="3.5" data-path="understanding-distributions.html"><a href="understanding-distributions.html#missing-data-and-skip-patterns"><i class="fa fa-check"></i><b>3.5</b> Missing data and skip patterns</a></li>
<li class="chapter" data-level="3.6" data-path="understanding-distributions.html"><a href="understanding-distributions.html#exercises"><i class="fa fa-check"></i><b>3.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="central-tendency-and-dispersion.html"><a href="central-tendency-and-dispersion.html"><i class="fa fa-check"></i><b>4</b> Central Tendency and Dispersion</a>
<ul>
<li class="chapter" data-level="4.1" data-path="central-tendency-and-dispersion.html"><a href="central-tendency-and-dispersion.html#central-tendency"><i class="fa fa-check"></i><b>4.1</b> Central tendency</a></li>
<li class="chapter" data-level="4.2" data-path="central-tendency-and-dispersion.html"><a href="central-tendency-and-dispersion.html#dispersion"><i class="fa fa-check"></i><b>4.2</b> Dispersion</a></li>
<li class="chapter" data-level="4.3" data-path="central-tendency-and-dispersion.html"><a href="central-tendency-and-dispersion.html#weighted-design-correct-summaries"><i class="fa fa-check"></i><b>4.3</b> Weighted, design-correct summaries</a></li>
<li class="chapter" data-level="4.4" data-path="central-tendency-and-dispersion.html"><a href="central-tendency-and-dispersion.html#outliers-and-the-unit-of-analysis"><i class="fa fa-check"></i><b>4.4</b> Outliers and the unit of analysis</a></li>
<li class="chapter" data-level="4.5" data-path="central-tendency-and-dispersion.html"><a href="central-tendency-and-dispersion.html#practice-exercises-1"><i class="fa fa-check"></i><b>4.5</b> Practice exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="bivariate-analysis.html"><a href="bivariate-analysis.html"><i class="fa fa-check"></i><b>5</b> Bivariate Analysis</a>
<ul>
<li class="chapter" data-level="5.1" data-path="bivariate-analysis.html"><a href="bivariate-analysis.html#choosing-the-right-bivariate-tool"><i class="fa fa-check"></i><b>5.1</b> Choosing the right bivariate tool</a></li>
<li class="chapter" data-level="5.2" data-path="bivariate-analysis.html"><a href="bivariate-analysis.html#categorical-categorical-cross-tabulations"><i class="fa fa-check"></i><b>5.2</b> Categorical × categorical: cross-tabulations</a></li>
<li class="chapter" data-level="5.3" data-path="bivariate-analysis.html"><a href="bivariate-analysis.html#continuous-categorical-comparing-group-means"><i class="fa fa-check"></i><b>5.3</b> Continuous × categorical: comparing group means</a></li>
<li class="chapter" data-level="5.4" data-path="bivariate-analysis.html"><a href="bivariate-analysis.html#continuous-continuous-scatterplots-and-trends"><i class="fa fa-check"></i><b>5.4</b> Continuous × continuous: scatterplots and trends</a></li>
<li class="chapter" data-level="5.5" data-path="bivariate-analysis.html"><a href="bivariate-analysis.html#testing-association-with-chi-squared-tests"><i class="fa fa-check"></i><b>5.5</b> Testing association with chi-squared tests</a></li>
<li class="chapter" data-level="5.6" data-path="bivariate-analysis.html"><a href="bivariate-analysis.html#practice-exercises-2"><i class="fa fa-check"></i><b>5.6</b> Practice exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html"><i class="fa fa-check"></i><b>6</b> Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="6.1" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#preparing-variables-for-analysis"><i class="fa fa-check"></i><b>6.1</b> Preparing variables for analysis</a></li>
<li class="chapter" data-level="6.2" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#correlation-and-simple-regression"><i class="fa fa-check"></i><b>6.2</b> Correlation and simple regression</a></li>
<li class="chapter" data-level="6.3" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#survey-weighted-regression-for-population-inference"><i class="fa fa-check"></i><b>6.3</b> Survey-weighted regression for population inference</a></li>
<li class="chapter" data-level="6.4" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#practice-exercises-3"><i class="fa fa-check"></i><b>6.4</b> Practice exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html"><i class="fa fa-check"></i><b>7</b> Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="7.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#the-multiple-regression-model-and-its-interpretation"><i class="fa fa-check"></i><b>7.1</b> The multiple regression model and its interpretation</a></li>
<li class="chapter" data-level="7.2" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#data-and-analysis-sample"><i class="fa fa-check"></i><b>7.2</b> Data and analysis sample</a></li>
<li class="chapter" data-level="7.3" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#building-a-multiple-regression-model"><i class="fa fa-check"></i><b>7.3</b> Building a multiple regression model</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#comparing-coefficients-across-models"><i class="fa fa-check"></i><b>7.3.1</b> Comparing coefficients across models</a></li>
<li class="chapter" data-level="7.3.2" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#interpreting-categorical-predictors"><i class="fa fa-check"></i><b>7.3.2</b> Interpreting categorical predictors</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#extensions-interactions-and-non-linear-effects"><i class="fa fa-check"></i><b>7.4</b> Extensions: interactions and non-linear effects</a></li>
<li class="chapter" data-level="7.5" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#reporting-results"><i class="fa fa-check"></i><b>7.5</b> Reporting results</a></li>
<li class="chapter" data-level="7.6" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#practice-exercises-4"><i class="fa fa-check"></i><b>7.6</b> Practice exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>8</b> Logistic Regression</a>
<ul>
<li class="chapter" data-level="8.1" data-path="logistic-regression.html"><a href="logistic-regression.html#what-logistic-regression-models"><i class="fa fa-check"></i><b>8.1</b> What logistic regression models</a></li>
<li class="chapter" data-level="8.2" data-path="logistic-regression.html"><a href="logistic-regression.html#simple-versus-multiple-logistic-regression"><i class="fa fa-check"></i><b>8.2</b> Simple versus multiple logistic regression</a></li>
<li class="chapter" data-level="8.3" data-path="logistic-regression.html"><a href="logistic-regression.html#data"><i class="fa fa-check"></i><b>8.3</b> Data</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="logistic-regression.html"><a href="logistic-regression.html#import-subset-and-keep-only-needed-variables"><i class="fa fa-check"></i><b>8.3.1</b> Import, subset, and keep only needed variables</a></li>
<li class="chapter" data-level="8.3.2" data-path="logistic-regression.html"><a href="logistic-regression.html#recode-variables-labels-reference-levels"><i class="fa fa-check"></i><b>8.3.2</b> Recode variables (labels + reference levels)</a></li>
<li class="chapter" data-level="8.3.3" data-path="logistic-regression.html"><a href="logistic-regression.html#why-we-need-survey-design-information"><i class="fa fa-check"></i><b>8.3.3</b> Why we need survey design information</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="logistic-regression.html"><a href="logistic-regression.html#simple-logistic-regression"><i class="fa fa-check"></i><b>8.4</b> Simple Logistic Regression</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="logistic-regression.html"><a href="logistic-regression.html#continuous-predictor-childs-age"><i class="fa fa-check"></i><b>8.4.1</b> Continuous predictor: child’s age</a></li>
<li class="chapter" data-level="8.4.2" data-path="logistic-regression.html"><a href="logistic-regression.html#categorical-predictor-example-books"><i class="fa fa-check"></i><b>8.4.2</b> Categorical predictor example: Books</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="logistic-regression.html"><a href="logistic-regression.html#multiple-binary-logistic-regression"><i class="fa fa-check"></i><b>8.5</b> Multiple binary logistic regression</a></li>
<li class="chapter" data-level="8.6" data-path="logistic-regression.html"><a href="logistic-regression.html#interaction"><i class="fa fa-check"></i><b>8.6</b> Interaction</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="logistic-regression.html"><a href="logistic-regression.html#interpretation-of-age-sex-and-the-agesex-interaction"><i class="fa fa-check"></i><b>8.6.1</b> Interpretation of age, sex, and the age*sex interaction</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="logistic-regression.html"><a href="logistic-regression.html#reporting-results-1"><i class="fa fa-check"></i><b>8.7</b> Reporting Results</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"><p>AFLEARN
Introduction to R using ICAN-ICAR 2025 Survey Data</p></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="understanding-distributions" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Chapter 3</span> Understanding distributions<a href="understanding-distributions.html#understanding-distributions" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Large survey datasets contain many variables and many observations. To learn from such data, you need tools that summarise patterns clearly and accurately. This chapter introduces distributions—the way a variable’s values are spread across the sample—and shows how to describe distributions using tables, summary statistics, and simple plots. Because the ICAN-ICAR data come from a complex survey, we also show how to produce weighted summaries that reflect the target population.</p>
<div id="getting-oriented-to-the-data" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Getting oriented to the data<a href="understanding-distributions.html#getting-oriented-to-the-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Firstly, check the number of rows and columns to get a sense of how big the data.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="understanding-distributions.html#cb7-1" tabindex="-1"></a><span class="fu">dim</span>(dat)       <span class="co"># rows and columns</span></span></code></pre></div>
<pre><code>## [1] 89141   142</code></pre>
<p>This is quite big. A good idea from here is to subset to the variables that we want to explore. The <code>dplyr</code> package has a <code>select</code> function that allows one to select and rearrange variables. For this session, we focus only on the child’s age, parent’s age, gender, enrollment status, and whether or not the child has met the minimum proficiency level for both numeracy and literacy.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="understanding-distributions.html#cb9-1" tabindex="-1"></a>dat <span class="ot">=</span> dat <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="understanding-distributions.html#cb9-2" tabindex="-1"></a>  <span class="fu">select</span>(CountryName, Location, HHID,VillageID, ChildID, Tier_One_Unit,</span>
<span id="cb9-3"><a href="understanding-distributions.html#cb9-3" tabindex="-1"></a>         ch02, ch03, ch06a, ch06b, enr_status, pt02b,</span>
<span id="cb9-4"><a href="understanding-distributions.html#cb9-4" tabindex="-1"></a>         pt01b, ch04a, MPL_both, HH_Weight_Provided) </span></code></pre></div>
<p>One can use the <code>skim()</code> function from <code>skimr</code> package to attain a broad view of the data and get useful summary statistics on each variable. It is useful because it handles data of all types and it is an alternative to <code>summary()</code>.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="understanding-distributions.html#cb10-1" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb10-2"><a href="understanding-distributions.html#cb10-2" tabindex="-1"></a></span>
<span id="cb10-3"><a href="understanding-distributions.html#cb10-3" tabindex="-1"></a>dat <span class="sc">|&gt;</span> </span>
<span id="cb10-4"><a href="understanding-distributions.html#cb10-4" tabindex="-1"></a>  <span class="fu">skim</span>()</span></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-5">Table 3.1: </span>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">dat</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">89141</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">16</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">7</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">9</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<colgroup>
<col width="19%" />
<col width="13%" />
<col width="19%" />
<col width="5%" />
<col width="5%" />
<col width="8%" />
<col width="12%" />
<col width="15%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">CountryName</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">10</td>
<td align="right">0</td>
<td align="right">11</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">Location</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">HHID</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">41</td>
<td align="right">41</td>
<td align="right">0</td>
<td align="right">54777</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">VillageID</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">4</td>
<td align="right">0</td>
<td align="right">627</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">ChildID</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">48</td>
<td align="right">66</td>
<td align="right">0</td>
<td align="right">89141</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">Tier_One_Unit</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">27</td>
<td align="right">0</td>
<td align="right">267</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">enr_status</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">13</td>
<td align="right">18</td>
<td align="right">0</td>
<td align="right">3</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table style="width:100%;">
<colgroup>
<col width="18%" />
<col width="9%" />
<col width="13%" />
<col width="7%" />
<col width="7%" />
<col width="5%" />
<col width="6%" />
<col width="7%" />
<col width="7%" />
<col width="8%" />
<col width="5%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">ch02</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">10.04</td>
<td align="right">3.22</td>
<td align="right">5.00</td>
<td align="right">7.00</td>
<td align="right">10.00</td>
<td align="right">13.00</td>
<td align="right">16.00</td>
<td align="left">▇▆▆▅▅</td>
</tr>
<tr class="even">
<td align="left">ch03</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">1.49</td>
<td align="right">0.50</td>
<td align="right">1.00</td>
<td align="right">1.00</td>
<td align="right">1.00</td>
<td align="right">2.00</td>
<td align="right">2.00</td>
<td align="left">▇▁▁▁▇</td>
</tr>
<tr class="odd">
<td align="left">ch06a</td>
<td align="right">9915</td>
<td align="right">0.89</td>
<td align="right">4.15</td>
<td align="right">2.91</td>
<td align="right">0.00</td>
<td align="right">2.00</td>
<td align="right">4.00</td>
<td align="right">6.00</td>
<td align="right">13.00</td>
<td align="left">▇▇▃▃▁</td>
</tr>
<tr class="even">
<td align="left">ch06b</td>
<td align="right">9909</td>
<td align="right">0.89</td>
<td align="right">1.29</td>
<td align="right">0.52</td>
<td align="right">1.00</td>
<td align="right">1.00</td>
<td align="right">1.00</td>
<td align="right">2.00</td>
<td align="right">3.00</td>
<td align="left">▇▁▂▁▁</td>
</tr>
<tr class="odd">
<td align="left">pt02b</td>
<td align="right">39813</td>
<td align="right">0.55</td>
<td align="right">42.70</td>
<td align="right">9.56</td>
<td align="right">18.00</td>
<td align="right">36.00</td>
<td align="right">41.00</td>
<td align="right">48.00</td>
<td align="right">80.00</td>
<td align="left">▂▇▆▂▁</td>
</tr>
<tr class="even">
<td align="left">pt01b</td>
<td align="right">25863</td>
<td align="right">0.71</td>
<td align="right">35.87</td>
<td align="right">8.01</td>
<td align="right">18.00</td>
<td align="right">30.00</td>
<td align="right">35.00</td>
<td align="right">40.00</td>
<td align="right">80.00</td>
<td align="left">▅▇▂▁▁</td>
</tr>
<tr class="odd">
<td align="left">ch04a</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">1.04</td>
<td align="right">0.22</td>
<td align="right">1.00</td>
<td align="right">1.00</td>
<td align="right">1.00</td>
<td align="right">1.00</td>
<td align="right">4.00</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td align="left">MPL_both</td>
<td align="right">3</td>
<td align="right">1.00</td>
<td align="right">0.29</td>
<td align="right">0.45</td>
<td align="right">0.00</td>
<td align="right">0.00</td>
<td align="right">0.00</td>
<td align="right">1.00</td>
<td align="right">1.00</td>
<td align="left">▇▁▁▁▃</td>
</tr>
<tr class="odd">
<td align="left">HH_Weight_Provided</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">2923.45</td>
<td align="right">3495.25</td>
<td align="right">0.42</td>
<td align="right">540.31</td>
<td align="right">2009.69</td>
<td align="right">3642.96</td>
<td align="right">52586.05</td>
<td align="left">▇▁▁▁▁</td>
</tr>
</tbody>
</table>
<p><em>complete_rate</em> tells us the proportion of rows that are not missing for that particular variable. For instance, <code>pt02b</code> has only <span class="math inline">\(55,4\%\)</span> of rows that have entries. In other words, this is equivalent to <span class="math inline">\(39813\)</span> missings (see also, <em>n_missing)</em> out of the <span class="math inline">\(89141\)</span> rows. It is important to see that if one does not specify correctly the variable type, then <code>skim()</code> will not pick that up. The child’s gender, <code>ch03</code>, is being recognized as a continuous variable instead of a categorical variable. Therefore, one should make sure that the variables are in their correct type to ensure correct variable summaries .</p>
</div>
<div id="levels-of-measurement" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Levels of measurement<a href="understanding-distributions.html#levels-of-measurement" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Any variable is composed of two or more categories or attributes. Thus the child’s gender is a variable with the categories male and female, country of birth is a variable with the categories being particular countries. The level of measurement of variables refers to how the categories of the variable relate to one another. There are three main levels of measurement: continuous, ordinal and categorical. Three characteristics of the categories of a variable determine its level of measurement:</p>
<ol style="list-style-type: decimal">
<li>whether there are different categories;</li>
<li>whether the categories can be rank ordered;</li>
<li>whether the differences or intervals between each category can be specified in a meaningful numerical sense.</li>
</ol>
<div id="continuous-level" class="section level3 hasAnchor" number="3.2.1">
<h3><span class="header-section-number">3.2.1</span> Continuous level<a href="understanding-distributions.html#continuous-level" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A continuous variable is one in which the categories can be ranked from low to high in some meaningful way. In addition to ordering the categories from low to high it is possible to specify the amount of difference between the categories or values. The child’s age, when measured in years, is an example of a continuous variable. We rank-order the categories of age (in years) from youngest (lowest) to oldest (highest). Furthermore, we can specify the amount of difference between the categories. The difference between the category “9 years old” and the category “13 years old” is 4 years. Other examples would be the number of household members, time taken to complete the numeracy assessment, and the numeracy score of the child.</p>
<p>We use the 5 number summary (box plot can also suffice) and a histogram to describe the distribution of continuous variables. In our data, we only have the parent’s age and child’s age as continuous variables.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="understanding-distributions.html#cb11-1" tabindex="-1"></a><span class="co"># 5 number summary </span></span>
<span id="cb11-2"><a href="understanding-distributions.html#cb11-2" tabindex="-1"></a>dat <span class="sc">|&gt;</span> </span>
<span id="cb11-3"><a href="understanding-distributions.html#cb11-3" tabindex="-1"></a>  <span class="fu">select</span>(ch02, pt02b, pt01b) <span class="sc">|&gt;</span></span>
<span id="cb11-4"><a href="understanding-distributions.html#cb11-4" tabindex="-1"></a>  <span class="fu">skim</span>()</span></code></pre></div>
<table>
<caption><span id="tab:continuous-summaries">Table 3.2: </span>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">select(dat, ch02, pt02b, …</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">89141</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">3</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">numeric</td>
<td align="left">3</td>
</tr>
<tr class="odd">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<colgroup>
<col width="18%" />
<col width="13%" />
<col width="18%" />
<col width="8%" />
<col width="6%" />
<col width="4%" />
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="6%" />
<col width="8%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">ch02</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">10.04</td>
<td align="right">3.22</td>
<td align="right">5</td>
<td align="right">7</td>
<td align="right">10</td>
<td align="right">13</td>
<td align="right">16</td>
<td align="left">▇▆▆▅▅</td>
</tr>
<tr class="even">
<td align="left">pt02b</td>
<td align="right">39813</td>
<td align="right">0.55</td>
<td align="right">42.70</td>
<td align="right">9.56</td>
<td align="right">18</td>
<td align="right">36</td>
<td align="right">41</td>
<td align="right">48</td>
<td align="right">80</td>
<td align="left">▂▇▆▂▁</td>
</tr>
<tr class="odd">
<td align="left">pt01b</td>
<td align="right">25863</td>
<td align="right">0.71</td>
<td align="right">35.87</td>
<td align="right">8.01</td>
<td align="right">18</td>
<td align="right">30</td>
<td align="right">35</td>
<td align="right">40</td>
<td align="right">80</td>
<td align="left">▅▇▂▁▁</td>
</tr>
</tbody>
</table>
<p>The typical age in years the children belong is <span class="math inline">\(10\)</span> years old, while it is <span class="math inline">\(36\)</span> and <span class="math inline">\(43\)</span> years old for the mother and father respectively. The child’s age is spread fairly evenly across the age categories relative to both the mother and father’s ages (see the standard deviation). If one had to order the children by age from the youngest (<span class="math inline">\(5\)</span>) to the oldest (<span class="math inline">\(16\)</span>), then the middle child would be <span class="math inline">\(10\)</span> years old.</p>
<p>Now, let us assess whether the categories of each variable tend to cluster towards the low or the high end. And possibly identify the potential outliers.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="understanding-distributions.html#cb12-1" tabindex="-1"></a><span class="co"># Histograms and box plot </span></span>
<span id="cb12-2"><a href="understanding-distributions.html#cb12-2" tabindex="-1"></a><span class="do">## child&#39;s age</span></span>
<span id="cb12-3"><a href="understanding-distributions.html#cb12-3" tabindex="-1"></a><span class="fu">ggplot</span>(dat, <span class="fu">aes</span>(<span class="at">x =</span> ch02)) <span class="sc">+</span></span>
<span id="cb12-4"><a href="understanding-distributions.html#cb12-4" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb12-5"><a href="understanding-distributions.html#cb12-5" tabindex="-1"></a>    <span class="at">bins =</span> <span class="dv">20</span>,</span>
<span id="cb12-6"><a href="understanding-distributions.html#cb12-6" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(count <span class="sc">/</span> <span class="fu">sum</span>(count) <span class="sc">*</span> <span class="dv">100</span>)),</span>
<span id="cb12-7"><a href="understanding-distributions.html#cb12-7" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">&quot;gold&quot;</span></span>
<span id="cb12-8"><a href="understanding-distributions.html#cb12-8" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb12-9"><a href="understanding-distributions.html#cb12-9" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Age (years)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Percentage (%)&quot;</span>,</span>
<span id="cb12-10"><a href="understanding-distributions.html#cb12-10" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Child&#39;s age histogram with percentage&quot;</span>) <span class="sc">+</span></span>
<span id="cb12-11"><a href="understanding-distributions.html#cb12-11" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:fig-age-hist-1"></span>
<img src="figs/fig-age-hist-1.png" alt="Distribution of child age in the ICAN-ICAR sample." width="576" />
<p class="caption">
Figure 3.1: Distribution of child age in the ICAN-ICAR sample.
</p>
</div>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="understanding-distributions.html#cb13-1" tabindex="-1"></a><span class="do">## father&#39;s age </span></span>
<span id="cb13-2"><a href="understanding-distributions.html#cb13-2" tabindex="-1"></a><span class="fu">ggplot</span>(dat, <span class="fu">aes</span>(<span class="at">x =</span> pt02b)) <span class="sc">+</span></span>
<span id="cb13-3"><a href="understanding-distributions.html#cb13-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb13-4"><a href="understanding-distributions.html#cb13-4" tabindex="-1"></a>    <span class="at">bins =</span> <span class="dv">20</span>,</span>
<span id="cb13-5"><a href="understanding-distributions.html#cb13-5" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(count <span class="sc">/</span> <span class="fu">sum</span>(count) <span class="sc">*</span> <span class="dv">100</span>)),</span>
<span id="cb13-6"><a href="understanding-distributions.html#cb13-6" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">&quot;skyblue&quot;</span></span>
<span id="cb13-7"><a href="understanding-distributions.html#cb13-7" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb13-8"><a href="understanding-distributions.html#cb13-8" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Age (years)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Percentage (%)&quot;</span>,</span>
<span id="cb13-9"><a href="understanding-distributions.html#cb13-9" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Father&#39;s age histogram with percentage&quot;</span>) <span class="sc">+</span></span>
<span id="cb13-10"><a href="understanding-distributions.html#cb13-10" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:fig-age-hist-2"></span>
<img src="figs/fig-age-hist-2.png" alt="Distribution of child age in the ICAN-ICAR sample." width="576" />
<p class="caption">
Figure 3.2: Distribution of child age in the ICAN-ICAR sample.
</p>
</div>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="understanding-distributions.html#cb14-1" tabindex="-1"></a><span class="do">## mother&#39;s age</span></span>
<span id="cb14-2"><a href="understanding-distributions.html#cb14-2" tabindex="-1"></a><span class="fu">ggplot</span>(dat, <span class="fu">aes</span>(<span class="at">x =</span> pt01b)) <span class="sc">+</span></span>
<span id="cb14-3"><a href="understanding-distributions.html#cb14-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb14-4"><a href="understanding-distributions.html#cb14-4" tabindex="-1"></a>    <span class="at">bins =</span> <span class="dv">20</span>,</span>
<span id="cb14-5"><a href="understanding-distributions.html#cb14-5" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(count <span class="sc">/</span> <span class="fu">sum</span>(count) <span class="sc">*</span> <span class="dv">100</span>)),</span>
<span id="cb14-6"><a href="understanding-distributions.html#cb14-6" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">&quot;magenta&quot;</span></span>
<span id="cb14-7"><a href="understanding-distributions.html#cb14-7" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb14-8"><a href="understanding-distributions.html#cb14-8" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Age (years)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Percentage (%)&quot;</span>,</span>
<span id="cb14-9"><a href="understanding-distributions.html#cb14-9" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Mother&#39;s age histogram with percentage&quot;</span>) <span class="sc">+</span></span>
<span id="cb14-10"><a href="understanding-distributions.html#cb14-10" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:fig-age-hist-3"></span>
<img src="figs/fig-age-hist-3.png" alt="Distribution of child age in the ICAN-ICAR sample." width="576" />
<p class="caption">
Figure 3.3: Distribution of child age in the ICAN-ICAR sample.
</p>
</div>
<p>For the child’s age there is no evidence clustering - the variable is spread fairly evenly across the categories. Both the mother’s and father’s age cluster at the lower end of their respective distributions, with tails on the high end.</p>
</div>
<div id="ordinal-level" class="section level3 hasAnchor" number="3.2.2">
<h3><span class="header-section-number">3.2.2</span> Ordinal level<a href="understanding-distributions.html#ordinal-level" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>An ordinal variable is one where we can rank-order categories from low to high. However, we cannot specify in numeric terms how much difference there is between the categories. For example, when the age variable has categories such as “child”, “adolescent”, “young adult”, “middle aged” and “elderly” the variable is measured at the ordinal level. The categories can be ordered from youngest to eldest but we cannot specify precisely the age gap between people in different categories. Measuring the child’s difficulty in their eyesight as “no difficulty”, “some difficulty”, and “a lot of difficulty” would produce an ordinal variable.</p>
<p>Typically, one can describe the distribution of an ordinal variable by asking about the frequency of children belonging to particular categories, asking which categories have a lot of cases and which have fewer cases. In that a frequency table will suffice.</p>
<p>Since the categories of ordinal variables can be ranked these categories should be put in their correct rank order in a frequency table. Failure to do so will distort both patterns in the data and statistics used to summarise them.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="understanding-distributions.html#cb15-1" tabindex="-1"></a><span class="co"># first insert appropriate labels </span></span>
<span id="cb15-2"><a href="understanding-distributions.html#cb15-2" tabindex="-1"></a>dat <span class="ot">=</span> dat <span class="sc">|&gt;</span></span>
<span id="cb15-3"><a href="understanding-distributions.html#cb15-3" tabindex="-1"></a>        <span class="fu">mutate</span>(</span>
<span id="cb15-4"><a href="understanding-distributions.html#cb15-4" tabindex="-1"></a>          <span class="at">ch04a =</span> <span class="fu">as.character</span>(ch04a), </span>
<span id="cb15-5"><a href="understanding-distributions.html#cb15-5" tabindex="-1"></a>          <span class="at">ch04a =</span> <span class="fu">case_when</span>(</span>
<span id="cb15-6"><a href="understanding-distributions.html#cb15-6" tabindex="-1"></a>            ch04a <span class="sc">==</span> <span class="st">&quot;1&quot;</span> <span class="sc">~</span> <span class="st">&quot;No difficulty&quot;</span>, </span>
<span id="cb15-7"><a href="understanding-distributions.html#cb15-7" tabindex="-1"></a>            ch04a <span class="sc">==</span> <span class="st">&quot;2&quot;</span> <span class="sc">~</span> <span class="st">&quot;Some difficulty&quot;</span>, </span>
<span id="cb15-8"><a href="understanding-distributions.html#cb15-8" tabindex="-1"></a>            ch04a <span class="sc">==</span> <span class="st">&quot;3&quot;</span> <span class="sc">~</span> <span class="st">&quot;A lot of difficulty&quot;</span>, </span>
<span id="cb15-9"><a href="understanding-distributions.html#cb15-9" tabindex="-1"></a>            ch04a <span class="sc">==</span> <span class="st">&quot;4&quot;</span> <span class="sc">~</span> <span class="st">&quot;Cannot do at all&quot;</span>, </span>
<span id="cb15-10"><a href="understanding-distributions.html#cb15-10" tabindex="-1"></a>            <span class="cn">TRUE</span> <span class="sc">~</span> ch04a</span>
<span id="cb15-11"><a href="understanding-distributions.html#cb15-11" tabindex="-1"></a>          )</span>
<span id="cb15-12"><a href="understanding-distributions.html#cb15-12" tabindex="-1"></a>        )</span>
<span id="cb15-13"><a href="understanding-distributions.html#cb15-13" tabindex="-1"></a></span>
<span id="cb15-14"><a href="understanding-distributions.html#cb15-14" tabindex="-1"></a><span class="co"># convert to ordered factor </span></span>
<span id="cb15-15"><a href="understanding-distributions.html#cb15-15" tabindex="-1"></a>dat <span class="ot">=</span> dat <span class="sc">|&gt;</span></span>
<span id="cb15-16"><a href="understanding-distributions.html#cb15-16" tabindex="-1"></a>       <span class="fu">mutate</span>(</span>
<span id="cb15-17"><a href="understanding-distributions.html#cb15-17" tabindex="-1"></a>         <span class="at">ch04a =</span> <span class="fu">factor</span>(ch04a, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;No difficulty&quot;</span>, </span>
<span id="cb15-18"><a href="understanding-distributions.html#cb15-18" tabindex="-1"></a>                                          <span class="st">&quot;Some difficulty&quot;</span>, </span>
<span id="cb15-19"><a href="understanding-distributions.html#cb15-19" tabindex="-1"></a>                                          <span class="st">&quot;A lot of difficulty&quot;</span>, </span>
<span id="cb15-20"><a href="understanding-distributions.html#cb15-20" tabindex="-1"></a>                                          <span class="st">&quot;Cannot do at all&quot;</span>), </span>
<span id="cb15-21"><a href="understanding-distributions.html#cb15-21" tabindex="-1"></a>                                 <span class="at">ordered =</span> <span class="cn">TRUE</span>)</span>
<span id="cb15-22"><a href="understanding-distributions.html#cb15-22" tabindex="-1"></a>       )</span></code></pre></div>
<p>Now, we are set to create a frequency table for the eyesight variable.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="understanding-distributions.html#cb16-1" tabindex="-1"></a>dat <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a href="understanding-distributions.html#cb16-2" tabindex="-1"></a>  <span class="fu">count</span>(ch04a) <span class="sc">|&gt;</span></span>
<span id="cb16-3"><a href="understanding-distributions.html#cb16-3" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb16-4"><a href="understanding-distributions.html#cb16-4" tabindex="-1"></a>    <span class="at">percent =</span> <span class="dv">100</span><span class="sc">*</span>(n<span class="sc">/</span><span class="fu">sum</span>(n))</span>
<span id="cb16-5"><a href="understanding-distributions.html#cb16-5" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 4 × 3
##   ch04a                   n percent
##   &lt;ord&gt;               &lt;int&gt;   &lt;dbl&gt;
## 1 No difficulty       86537  97.1  
## 2 Some difficulty      2185   2.45 
## 3 A lot of difficulty   302   0.339
## 4 Cannot do at all      117   0.131</code></pre>
<p>Pay attention to the description of <code>ch04a</code> - R recognizes it as an &lt;ord&gt; now. From the table, we can see that only <span class="math inline">\(2,9\%\)</span> children in the sample have some form of difficulty in their eyesight, even after wearing glasses. One category in this variable accounts for the bulk of the cases. One can say that this sample is fairly homogeneous with regards to <code>ch04a</code> . In other words, the frequency table is not symmetrical because most of the cases are clustered at one end of a distribution of this ordinal variable. When cases are clustered at the low end the distribution is positively skewed.</p>
<p>Sometimes ordinal variables can often be displayed effectively with graphs. Now, we can going to show how <code>ch04a</code> is distributed using a bar graph.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="understanding-distributions.html#cb18-1" tabindex="-1"></a>dat <span class="sc">|&gt;</span></span>
<span id="cb18-2"><a href="understanding-distributions.html#cb18-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> ch04a))<span class="sc">+</span></span>
<span id="cb18-3"><a href="understanding-distributions.html#cb18-3" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">&quot;violet&quot;</span>)<span class="sc">+</span></span>
<span id="cb18-4"><a href="understanding-distributions.html#cb18-4" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb18-5"><a href="understanding-distributions.html#cb18-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Vertical bar chart with counts&quot;</span>, </span>
<span id="cb18-6"><a href="understanding-distributions.html#cb18-6" tabindex="-1"></a>           <span class="at">x =</span> <span class="st">&quot;Eyesight&quot;</span>)</span></code></pre></div>
<p><img src="figs/bar-graph-eyesight-1.png" width="672" />
While the mode as a measure of central tendency can be for ordinal variables the median is preferred because it takes account of the fact that children can be ranked on ordinal variables. The median is worked out by ranking each case in a distribution from low to high on the variable and finding the middle child. Whatever the category the middle child belongs to is the median category. In large scale survey research, this is done by obtaining a frequency table, as we have done above, for the variable and examining the cumulative percentage column. To locate the median simply look down this column until the cumulative percentage nudges over <span class="math inline">\(50\)</span> percent and then look at the category of the variable that corresponds to this. In <code>ch04a</code> case, the middle child is the one with no difficulty in eyesight.</p>
</div>
<div id="categorical-level" class="section level3 hasAnchor" number="3.2.3">
<h3><span class="header-section-number">3.2.3</span> Categorical level<a href="understanding-distributions.html#categorical-level" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A categorical variable is one where the different categories have no set rank-order. With a categorical variable it makes no sense to say that the categories can be ordered from low to high in some sense. The type of school the child goes to (<code>ch06b</code>) is a categorical variable where categories have no natural rank-order.</p>
<p>Two main types of summarising statistics are used for categorical variables to describe their distributions: those used to indicate typical values (central tendency), and those used to indicate group variation With categorical variables the only way to indicate the typical response is to identify the single most common response. The most common response, the one with the largest number of cases, is called the mode.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="understanding-distributions.html#cb19-1" tabindex="-1"></a><span class="co"># firstly, give proper labels </span></span>
<span id="cb19-2"><a href="understanding-distributions.html#cb19-2" tabindex="-1"></a>dat <span class="ot">=</span> dat <span class="sc">|&gt;</span></span>
<span id="cb19-3"><a href="understanding-distributions.html#cb19-3" tabindex="-1"></a>        <span class="fu">mutate</span>(</span>
<span id="cb19-4"><a href="understanding-distributions.html#cb19-4" tabindex="-1"></a>          <span class="at">ch06b =</span> <span class="fu">as.character</span>(ch06b), </span>
<span id="cb19-5"><a href="understanding-distributions.html#cb19-5" tabindex="-1"></a>          <span class="at">ch06b =</span> <span class="fu">case_when</span>(</span>
<span id="cb19-6"><a href="understanding-distributions.html#cb19-6" tabindex="-1"></a>            ch06b <span class="sc">==</span> <span class="st">&quot;1&quot;</span> <span class="sc">~</span> <span class="st">&quot;Government&quot;</span>, </span>
<span id="cb19-7"><a href="understanding-distributions.html#cb19-7" tabindex="-1"></a>            ch06b <span class="sc">==</span> <span class="st">&quot;2&quot;</span> <span class="sc">~</span> <span class="st">&quot;Private&quot;</span>, </span>
<span id="cb19-8"><a href="understanding-distributions.html#cb19-8" tabindex="-1"></a>            ch06b <span class="sc">==</span> <span class="st">&quot;3&quot;</span> <span class="sc">~</span> <span class="st">&quot;Other&quot;</span>, </span>
<span id="cb19-9"><a href="understanding-distributions.html#cb19-9" tabindex="-1"></a>            <span class="cn">TRUE</span> <span class="sc">~</span> ch06b</span>
<span id="cb19-10"><a href="understanding-distributions.html#cb19-10" tabindex="-1"></a>          )</span>
<span id="cb19-11"><a href="understanding-distributions.html#cb19-11" tabindex="-1"></a>        )</span>
<span id="cb19-12"><a href="understanding-distributions.html#cb19-12" tabindex="-1"></a><span class="co"># create a frequency table</span></span>
<span id="cb19-13"><a href="understanding-distributions.html#cb19-13" tabindex="-1"></a>dat <span class="sc">|&gt;</span> </span>
<span id="cb19-14"><a href="understanding-distributions.html#cb19-14" tabindex="-1"></a>  <span class="fu">count</span>(ch06b) <span class="sc">|&gt;</span></span>
<span id="cb19-15"><a href="understanding-distributions.html#cb19-15" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percent =</span> <span class="dv">100</span><span class="sc">*</span>(n<span class="sc">/</span><span class="fu">sum</span>(n)))</span></code></pre></div>
<pre><code>## # A tibble: 4 × 3
##   ch06b          n percent
##   &lt;chr&gt;      &lt;int&gt;   &lt;dbl&gt;
## 1 Government 59007   66.2 
## 2 Other       2664    2.99
## 3 Private    17561   19.7 
## 4 &lt;NA&gt;        9909   11.1</code></pre>
<p>In the table above, the single most common response is “Government”, thus “Government” schools is the mode of the <code>ch04a</code>. But, sometimes using the mode to measure the typical response is problematic. Picking the most common response does not tell us how typical it is. In that case, we have to provide a way of summarising how diverse a group is. For categorical variables the appropriate measure of variation is the variation ratio. It is easily calculated by seeing what percentage of children are not in the model category. The variation ratio is normally expressed as a proportion. This is simply done by moving the decimal place on the percentage figure (percent not in modal category) two places to the left. Thus in the frequency table, the mode is “Government” which contains <span class="math inline">\(66,2\%\)</span> of the sample. The percentage not in the model category is therefore <span class="math inline">\(33.8\%\)</span>. The variation ratio therefore is <span class="math inline">\(0,33\)</span>.</p>
<p>It is desirable to use a measure of variation alongside a measure of central tendency. The measure of central tendency gives us an idea of what is typical while the measure of variation gives us a sense og how typical typical is. The more variation there is in a sample the less well the average summarises the sample. In the case of the variation ratio - the higher the variation ratio the more poorly the mode summarises the overall distribution of the categorical variable.</p>
<p>A bar chart is most appropriate graphical tool one can use to describe the distribution of a categorical variable.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="understanding-distributions.html#cb21-1" tabindex="-1"></a>dat <span class="sc">|&gt;</span></span>
<span id="cb21-2"><a href="understanding-distributions.html#cb21-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> ch06b))<span class="sc">+</span></span>
<span id="cb21-3"><a href="understanding-distributions.html#cb21-3" tabindex="-1"></a>  <span class="fu">geom_bar</span>(</span>
<span id="cb21-4"><a href="understanding-distributions.html#cb21-4" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(count <span class="sc">/</span> <span class="fu">sum</span>(count) <span class="sc">*</span> <span class="dv">100</span>)),</span>
<span id="cb21-5"><a href="understanding-distributions.html#cb21-5" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">&quot;violet&quot;</span></span>
<span id="cb21-6"><a href="understanding-distributions.html#cb21-6" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb21-7"><a href="understanding-distributions.html#cb21-7" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb21-8"><a href="understanding-distributions.html#cb21-8" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb21-9"><a href="understanding-distributions.html#cb21-9" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Horizontal bar chart with counts&quot;</span>, </span>
<span id="cb21-10"><a href="understanding-distributions.html#cb21-10" tabindex="-1"></a>            <span class="at">y=</span> <span class="st">&quot;School Type&quot;</span>)</span></code></pre></div>
<img src="figs/bar-graph-schooltype-1.png" width="672" />
The table below summarises the graphical representation that can be used to describe variables at each of the three levels of measurement. Consider these everytime.
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-8">Table 3.3: </span><span id="tab:unnamed-chunk-8">Table 3.4: </span>Graph type by level of measurement
</caption>
<thead>
<tr>
<th style="text-align:left;">
Graph type
</th>
<th style="text-align:center;">
Categorical
</th>
<th style="text-align:center;">
Ordinal
</th>
<th style="text-align:center;">
Continuous
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Bar charts
</td>
<td style="text-align:center;">
✓
</td>
<td style="text-align:center;">
✓
</td>
<td style="text-align:center;">
?
</td>
</tr>
<tr>
<td style="text-align:left;">
Line graphs
</td>
<td style="text-align:center;">
✗
</td>
<td style="text-align:center;">
?
</td>
<td style="text-align:center;">
✓
</td>
</tr>
<tr>
<td style="text-align:left;">
Area graph
</td>
<td style="text-align:center;">
✗
</td>
<td style="text-align:center;">
?
</td>
<td style="text-align:center;">
✓
</td>
</tr>
<tr>
<td style="text-align:left;">
Histogram
</td>
<td style="text-align:center;">
✗
</td>
<td style="text-align:center;">
✗
</td>
<td style="text-align:center;">
✓
</td>
</tr>
<tr>
<td style="text-align:left;">
Boxplot
</td>
<td style="text-align:center;">
✗
</td>
<td style="text-align:center;">
✓
</td>
<td style="text-align:center;">
✓
</td>
</tr>
<tr>
<td style="text-align:left;">
Pie chart
</td>
<td style="text-align:center;">
✓
</td>
<td style="text-align:center;">
✓
</td>
<td style="text-align:center;">
?
</td>
</tr>
</tbody>
</table>
<p>Also, the table below helps one to choose summary descriptive statistics for different levels of measurement</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-9">Table 3.5: </span><span id="tab:unnamed-chunk-9">Table 3.6: </span>Choosing summary descriptive statistics for different levels of measurement
</caption>
<thead>
<tr>
<th style="text-align:center;">
Category
</th>
<th style="text-align:center;">
Statistic
</th>
<th style="text-align:center;">
Categorical
</th>
<th style="text-align:center;">
Ordinal
</th>
<th style="text-align:center;">
Continuous
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
Averages
</td>
<td style="text-align:center;">
Mode
</td>
<td style="text-align:center;">
✓
</td>
<td style="text-align:center;">
?
</td>
<td style="text-align:center;">
?
</td>
</tr>
<tr>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
Median
</td>
<td style="text-align:center;">
✗
</td>
<td style="text-align:center;">
✓
</td>
<td style="text-align:center;">
?
</td>
</tr>
<tr>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
Mean
</td>
<td style="text-align:center;">
✗
</td>
<td style="text-align:center;">
✗
</td>
<td style="text-align:center;">
✓
</td>
</tr>
<tr>
<td style="text-align:center;">
Dispersion/variation
</td>
<td style="text-align:center;">
Variation ratio
</td>
<td style="text-align:center;">
✓
</td>
<td style="text-align:center;">
?
</td>
<td style="text-align:center;">
?
</td>
</tr>
<tr>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
Interquartile range
</td>
<td style="text-align:center;">
✗
</td>
<td style="text-align:center;">
✓
</td>
<td style="text-align:center;">
?
</td>
</tr>
<tr>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
Variance/standard deviation
</td>
<td style="text-align:center;">
✗
</td>
<td style="text-align:center;">
✗
</td>
<td style="text-align:center;">
✓
</td>
</tr>
<tr>
<td style="text-align:center;">
Symmetry
</td>
<td style="text-align:center;">
Graph/visual
</td>
<td style="text-align:center;">
✗
</td>
<td style="text-align:center;">
✓
</td>
<td style="text-align:center;">
✓
</td>
</tr>
<tr>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
Skewness statistic
</td>
<td style="text-align:center;">
✗
</td>
<td style="text-align:center;">
✗
</td>
<td style="text-align:center;">
✓
</td>
</tr>
<tr>
<td style="text-align:center;">
Kurtosis
</td>
<td style="text-align:center;">
Graph/visual
</td>
<td style="text-align:center;">
✗
</td>
<td style="text-align:center;">
✓
</td>
<td style="text-align:center;">
✓
</td>
</tr>
<tr>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
Kurtosis statistic
</td>
<td style="text-align:center;">
✗
</td>
<td style="text-align:center;">
✗
</td>
<td style="text-align:center;">
✓
</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="weighted-summaries-using-the-survey-design" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Weighted summaries using the survey design<a href="understanding-distributions.html#weighted-summaries-using-the-survey-design" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Unweighted summaries describe the sample. To describe the population, you must account for weights, clustering, and stratification.</p>
<p>We create a survey design object using the same structure used elsewhere in the course.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="understanding-distributions.html#cb22-1" tabindex="-1"></a><span class="fu">options</span>(</span>
<span id="cb22-2"><a href="understanding-distributions.html#cb22-2" tabindex="-1"></a>  <span class="at">survey.lonely.psu =</span> <span class="st">&quot;adjust&quot;</span>,</span>
<span id="cb22-3"><a href="understanding-distributions.html#cb22-3" tabindex="-1"></a>  <span class="at">survey.adjust.domain.lonely =</span> <span class="cn">TRUE</span></span>
<span id="cb22-4"><a href="understanding-distributions.html#cb22-4" tabindex="-1"></a>)</span>
<span id="cb22-5"><a href="understanding-distributions.html#cb22-5" tabindex="-1"></a></span>
<span id="cb22-6"><a href="understanding-distributions.html#cb22-6" tabindex="-1"></a>des_child_all <span class="ot">=</span> <span class="fu">svydesign</span>(</span>
<span id="cb22-7"><a href="understanding-distributions.html#cb22-7" tabindex="-1"></a>  <span class="at">ids     =</span> <span class="sc">~</span><span class="fu">interaction</span>(CountryName, VillageID) <span class="sc">+</span> HHID,</span>
<span id="cb22-8"><a href="understanding-distributions.html#cb22-8" tabindex="-1"></a>  <span class="at">strata  =</span> <span class="sc">~</span><span class="fu">interaction</span>(CountryName, Tier_One_Unit),</span>
<span id="cb22-9"><a href="understanding-distributions.html#cb22-9" tabindex="-1"></a>  <span class="at">weights =</span> <span class="sc">~</span>HH_Weight_Provided,</span>
<span id="cb22-10"><a href="understanding-distributions.html#cb22-10" tabindex="-1"></a>  <span class="at">data    =</span> dat,</span>
<span id="cb22-11"><a href="understanding-distributions.html#cb22-11" tabindex="-1"></a>  <span class="at">nest    =</span> <span class="cn">TRUE</span></span>
<span id="cb22-12"><a href="understanding-distributions.html#cb22-12" tabindex="-1"></a>)</span></code></pre></div>
<div id="weighted-proportions-and-means" class="section level3 hasAnchor" number="3.3.1">
<h3><span class="header-section-number">3.3.1</span> Weighted proportions and means<a href="understanding-distributions.html#weighted-proportions-and-means" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A weighted proportion of girls in the population:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="understanding-distributions.html#cb23-1" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span><span class="fu">I</span>(ch03 <span class="sc">==</span> <span class="dv">1</span>), des_child_all, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>##                      mean     SE
## I(ch03 == 1)FALSE 0.51713 0.0032
## I(ch03 == 1)TRUE  0.48287 0.0032</code></pre>
<p>Weighted means for several continuous variables:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="understanding-distributions.html#cb25-1" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>ch02 <span class="sc">+</span> pt02b <span class="sc">+</span> pt01b, des_child_all, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>##         mean     SE
## ch02   9.946 0.0336
## pt02b 41.196 0.1053
## pt01b 35.345 0.0920</code></pre>
</div>
<div id="weighted-frequency-tables" class="section level3 hasAnchor" number="3.3.2">
<h3><span class="header-section-number">3.3.2</span> Weighted frequency tables<a href="understanding-distributions.html#weighted-frequency-tables" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Weighted distributions use <code>svytable()</code>.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="understanding-distributions.html#cb27-1" tabindex="-1"></a>country_w <span class="ot">=</span> <span class="fu">svytable</span>(<span class="sc">~</span>CountryName, des_child_all)</span>
<span id="cb27-2"><a href="understanding-distributions.html#cb27-2" tabindex="-1"></a></span>
<span id="cb27-3"><a href="understanding-distributions.html#cb27-3" tabindex="-1"></a>country_w_tbl <span class="ot">=</span> <span class="fu">tibble</span>(</span>
<span id="cb27-4"><a href="understanding-distributions.html#cb27-4" tabindex="-1"></a>  <span class="at">CountryName =</span> <span class="fu">names</span>(country_w),</span>
<span id="cb27-5"><a href="understanding-distributions.html#cb27-5" tabindex="-1"></a>  <span class="at">weighted_n  =</span> <span class="fu">as.numeric</span>(country_w),</span>
<span id="cb27-6"><a href="understanding-distributions.html#cb27-6" tabindex="-1"></a>  <span class="at">percent     =</span> <span class="fu">as.numeric</span>(<span class="dv">100</span> <span class="sc">*</span> <span class="fu">prop.table</span>(country_w))</span>
<span id="cb27-7"><a href="understanding-distributions.html#cb27-7" tabindex="-1"></a>)</span></code></pre></div>
</div>
</div>
<div id="household-level-variables-in-a-child-level-file" class="section level2 hasAnchor" number="3.4">
<h2><span class="header-section-number">3.4</span> Household-level variables in a child-level file<a href="understanding-distributions.html#household-level-variables-in-a-child-level-file" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>When a household-level variable repeats across children, a child-level frequency table over-weights large households. A simple fix is to keep one record per household.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="understanding-distributions.html#cb28-1" tabindex="-1"></a>dat <span class="ot">=</span> dat <span class="sc">|&gt;</span></span>
<span id="cb28-2"><a href="understanding-distributions.html#cb28-2" tabindex="-1"></a>  <span class="fu">arrange</span>(HHID, ChildID) <span class="sc">|&gt;</span></span>
<span id="cb28-3"><a href="understanding-distributions.html#cb28-3" tabindex="-1"></a>  <span class="fu">group_by</span>(HHID) <span class="sc">|&gt;</span></span>
<span id="cb28-4"><a href="understanding-distributions.html#cb28-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">hh_first =</span> <span class="fu">row_number</span>() <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb28-5"><a href="understanding-distributions.html#cb28-5" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code></pre></div>
<p>For example, compare a child-level and household-level distribution of roof type (<code>hh07a</code>), if that variable is available in your extract.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="understanding-distributions.html#cb29-1" tabindex="-1"></a><span class="co"># child-level distribution (counts children)</span></span>
<span id="cb29-2"><a href="understanding-distributions.html#cb29-2" tabindex="-1"></a>dat <span class="sc">|&gt;</span></span>
<span id="cb29-3"><a href="understanding-distributions.html#cb29-3" tabindex="-1"></a>  <span class="fu">count</span>(hh07a) <span class="sc">|&gt;</span></span>
<span id="cb29-4"><a href="understanding-distributions.html#cb29-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percent =</span> <span class="dv">100</span> <span class="sc">*</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span>
<span id="cb29-5"><a href="understanding-distributions.html#cb29-5" tabindex="-1"></a></span>
<span id="cb29-6"><a href="understanding-distributions.html#cb29-6" tabindex="-1"></a><span class="co"># household-level distribution (counts households once)</span></span>
<span id="cb29-7"><a href="understanding-distributions.html#cb29-7" tabindex="-1"></a>dat <span class="sc">|&gt;</span></span>
<span id="cb29-8"><a href="understanding-distributions.html#cb29-8" tabindex="-1"></a>  <span class="fu">filter</span>(hh_first) <span class="sc">|&gt;</span></span>
<span id="cb29-9"><a href="understanding-distributions.html#cb29-9" tabindex="-1"></a>  <span class="fu">count</span>(hh07a) <span class="sc">|&gt;</span></span>
<span id="cb29-10"><a href="understanding-distributions.html#cb29-10" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percent =</span> <span class="dv">100</span> <span class="sc">*</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span></code></pre></div>
<p>To produce a weighted household-level distribution, subset the survey design to one row per household.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="understanding-distributions.html#cb30-1" tabindex="-1"></a><span class="fu">options</span>(</span>
<span id="cb30-2"><a href="understanding-distributions.html#cb30-2" tabindex="-1"></a>  <span class="at">survey.lonely.psu =</span> <span class="st">&quot;adjust&quot;</span>,</span>
<span id="cb30-3"><a href="understanding-distributions.html#cb30-3" tabindex="-1"></a>  <span class="at">survey.adjust.domain.lonely =</span> <span class="cn">TRUE</span></span>
<span id="cb30-4"><a href="understanding-distributions.html#cb30-4" tabindex="-1"></a>)</span>
<span id="cb30-5"><a href="understanding-distributions.html#cb30-5" tabindex="-1"></a></span>
<span id="cb30-6"><a href="understanding-distributions.html#cb30-6" tabindex="-1"></a>des_child_all <span class="ot">=</span> <span class="fu">svydesign</span>(</span>
<span id="cb30-7"><a href="understanding-distributions.html#cb30-7" tabindex="-1"></a>  <span class="at">ids     =</span> <span class="sc">~</span><span class="fu">interaction</span>(CountryName, VillageID) <span class="sc">+</span> HHID,</span>
<span id="cb30-8"><a href="understanding-distributions.html#cb30-8" tabindex="-1"></a>  <span class="at">strata  =</span> <span class="sc">~</span><span class="fu">interaction</span>(CountryName, Tier_One_Unit),</span>
<span id="cb30-9"><a href="understanding-distributions.html#cb30-9" tabindex="-1"></a>  <span class="at">weights =</span> <span class="sc">~</span>HH_Weight_Provided,</span>
<span id="cb30-10"><a href="understanding-distributions.html#cb30-10" tabindex="-1"></a>  <span class="at">data    =</span> dat,</span>
<span id="cb30-11"><a href="understanding-distributions.html#cb30-11" tabindex="-1"></a>  <span class="at">nest    =</span> <span class="cn">TRUE</span></span>
<span id="cb30-12"><a href="understanding-distributions.html#cb30-12" tabindex="-1"></a>)</span>
<span id="cb30-13"><a href="understanding-distributions.html#cb30-13" tabindex="-1"></a></span>
<span id="cb30-14"><a href="understanding-distributions.html#cb30-14" tabindex="-1"></a>des_household <span class="ot">=</span> <span class="fu">subset</span>(des_child_all, hh_first)</span>
<span id="cb30-15"><a href="understanding-distributions.html#cb30-15" tabindex="-1"></a></span>
<span id="cb30-16"><a href="understanding-distributions.html#cb30-16" tabindex="-1"></a>roof_w <span class="ot">=</span> <span class="fu">svytable</span>(<span class="sc">~</span>hh07a, des_household)</span>
<span id="cb30-17"><a href="understanding-distributions.html#cb30-17" tabindex="-1"></a></span>
<span id="cb30-18"><a href="understanding-distributions.html#cb30-18" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb30-19"><a href="understanding-distributions.html#cb30-19" tabindex="-1"></a>  <span class="at">roof_type =</span> <span class="fu">names</span>(roof_w),</span>
<span id="cb30-20"><a href="understanding-distributions.html#cb30-20" tabindex="-1"></a>  <span class="at">percent   =</span> <span class="fu">as.numeric</span>(<span class="dv">100</span> <span class="sc">*</span> <span class="fu">prop.table</span>(roof_w))</span>
<span id="cb30-21"><a href="understanding-distributions.html#cb30-21" tabindex="-1"></a>)</span></code></pre></div>
</div>
<div id="missing-data-and-skip-patterns" class="section level2 hasAnchor" number="3.5">
<h2><span class="header-section-number">3.5</span> Missing data and skip patterns<a href="understanding-distributions.html#missing-data-and-skip-patterns" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Missing values are common in survey data. In ICAN-ICAR, missingness often reflects skip patterns. For example, grade (<code>ch06a</code>) is usually recorded only for learners who are currently enrolled.</p>
<p>Start by checking how much is missing.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="understanding-distributions.html#cb31-1" tabindex="-1"></a>dat <span class="sc">|&gt;</span></span>
<span id="cb31-2"><a href="understanding-distributions.html#cb31-2" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb31-3"><a href="understanding-distributions.html#cb31-3" tabindex="-1"></a>    <span class="at">total =</span> <span class="fu">n</span>(),</span>
<span id="cb31-4"><a href="understanding-distributions.html#cb31-4" tabindex="-1"></a>    <span class="at">missing_ch06a =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(ch06a)),</span>
<span id="cb31-5"><a href="understanding-distributions.html#cb31-5" tabindex="-1"></a>    <span class="at">missing_pct =</span> <span class="dv">100</span> <span class="sc">*</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(ch06a)) <span class="sc">/</span> <span class="fu">n</span>()</span>
<span id="cb31-6"><a href="understanding-distributions.html#cb31-6" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##   total missing_ch06a missing_pct
##   &lt;int&gt;         &lt;int&gt;       &lt;dbl&gt;
## 1 89141          9915        11.1</code></pre>
<p>Then evaluate whether missingness aligns with enrolment status.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="understanding-distributions.html#cb33-1" tabindex="-1"></a>dat <span class="sc">|&gt;</span></span>
<span id="cb33-2"><a href="understanding-distributions.html#cb33-2" tabindex="-1"></a>  <span class="fu">group_by</span>(enr_status) <span class="sc">|&gt;</span></span>
<span id="cb33-3"><a href="understanding-distributions.html#cb33-3" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb33-4"><a href="understanding-distributions.html#cb33-4" tabindex="-1"></a>    <span class="at">total =</span> <span class="fu">n</span>(),</span>
<span id="cb33-5"><a href="understanding-distributions.html#cb33-5" tabindex="-1"></a>    <span class="at">missing_ch06a =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(ch06a)),</span>
<span id="cb33-6"><a href="understanding-distributions.html#cb33-6" tabindex="-1"></a>    <span class="at">missing_pct =</span> <span class="dv">100</span> <span class="sc">*</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(ch06a)) <span class="sc">/</span> <span class="fu">n</span>()</span>
<span id="cb33-7"><a href="understanding-distributions.html#cb33-7" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb33-8"><a href="understanding-distributions.html#cb33-8" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(total))</span></code></pre></div>
<pre><code>## # A tibble: 3 × 4
##   enr_status         total missing_ch06a missing_pct
##   &lt;chr&gt;              &lt;int&gt;         &lt;int&gt;       &lt;dbl&gt;
## 1 Currently Enrolled 79397           171       0.215
## 2 Never Enrolled      7517          7517     100    
## 3 Out of School       2227          2227     100</code></pre>
<p>You can also estimate weighted missingness rates by subgroup.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="understanding-distributions.html#cb35-1" tabindex="-1"></a><span class="fu">svyby</span>(</span>
<span id="cb35-2"><a href="understanding-distributions.html#cb35-2" tabindex="-1"></a>  <span class="sc">~</span><span class="fu">I</span>(<span class="fu">is.na</span>(ch06a)),</span>
<span id="cb35-3"><a href="understanding-distributions.html#cb35-3" tabindex="-1"></a>  <span class="sc">~</span>enr_status,</span>
<span id="cb35-4"><a href="understanding-distributions.html#cb35-4" tabindex="-1"></a>  des_child_all,</span>
<span id="cb35-5"><a href="understanding-distributions.html#cb35-5" tabindex="-1"></a>  svymean,</span>
<span id="cb35-6"><a href="understanding-distributions.html#cb35-6" tabindex="-1"></a>  <span class="at">na.rm =</span> <span class="cn">TRUE</span></span>
<span id="cb35-7"><a href="understanding-distributions.html#cb35-7" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>##                            enr_status I(is.na(ch06a))FALSE I(is.na(ch06a))TRUE
## Currently Enrolled Currently Enrolled            0.9991602        0.0008397509
## Never Enrolled         Never Enrolled            0.0000000        1.0000000000
## Out of School           Out of School            0.0000000        1.0000000000
##                    se.I(is.na(ch06a))FALSE se.I(is.na(ch06a))TRUE
## Currently Enrolled            0.0001091877           0.0001091877
## Never Enrolled                0.0000000000           0.0000000000
## Out of School                 0.0000000000           0.0000000000</code></pre>
</div>
<div id="exercises" class="section level2 hasAnchor" number="3.6">
<h2><span class="header-section-number">3.6</span> Exercises<a href="understanding-distributions.html#exercises" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Use the ICAN-ICAR data and the tools in this chapter to answer the questions below.</p>
<ol style="list-style-type: decimal">
<li>What proportion of the sample is rural (<code>Location == "Rural"</code>)? Compute both the unweighted and weighted estimate.</li>
<li>What is the unweighted and weighted mean child age (<code>ch02</code>) for enrolled learners (<code>enr_status == "Currently Enrolled"</code>)?</li>
<li>Create an age group variable (for example, <code>&lt;= 10</code> vs <code>&gt; 10</code>). What share of learners falls in each age group?</li>
<li>Produce a weighted frequency table for <code>Location</code> within one country of your choice.</li>
<li>Investigate missingness in <code>ch06a</code> by <code>residence</code> and by <code>sex</code>. Report the results as unweighted and weighted proportions.</li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="survey-design-sampling-and-weighting.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="central-tendency-and-dispersion.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/siphiwebogatsu/DF-draft/edit/main/02-understanding-distributions.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": "https://github.comsiphiwebogatsu/DF-draft/blob/main/02-understanding-distributions.Rmd",
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
